"""Build-only platform substitutions; the effect implementation stays shared.

Fail closed when the original hardware adapter changes unexpectedly. Generated
files are not authoritative sources and never modify the PSP working tree.
"""
from pathlib import Path
import struct

root = Path(__file__).resolve().parents[1]
psp = root.parent / 'psp-client'
if not (psp / 'milkdrop_gu.c').exists():
    psp = root / 'shared'  # Corresponding-source layout in the release folder.
out = root / 'generated'
out.mkdir(exist_ok=True)
source = (psp / 'milkdrop_gu.c').read_text()

def replace(old, new):
    global source
    if source.count(old) != 1:
        raise SystemExit(f'Xbox adapter needs review: {old[:90]!r}')
    source = source.replace(old, new)

replace('#include <pspgu.h>\n#include <pspge.h>\n#include <pspkernel.h>', '#include "visual_gpu.h"')
replace('return (void *)(uintptr_t)(0x04000000 + md_offset(index));', 'return xv_ram + md_offset(index);')
replace('if(tv && md_high_resolution && preset!=5)', 'if(0) /* Xbox has two full-color feedback surfaces. */')
replace('md_texture_base = tv ? 768*480*4 : 512*272*4;', 'md_texture_base = 768*480*4;')
replace('md_pixel_format = (preset!=5 && !tv && !md_high_resolution)?GU_PSM_8888:GU_PSM_5650;', 'md_pixel_format = GU_PSM_8888;')
replace('(void *)(uintptr_t)(0x44000000 + MD_TEXTURE_BASE)', '(void *)(xv_ram + MD_TEXTURE_BASE)')
replace('memset((void *)(xv_ram + MD_TEXTURE_BASE), 0, surfaces*MD_TEXTURE_BYTES);', 'memset((void *)(xv_ram + MD_TEXTURE_BASE), 0, surfaces*MD_TEXTURE_BYTES);sceKernelDcacheWritebackRange(xv_ram+MD_TEXTURE_BASE,surfaces*MD_TEXTURE_BYTES);')
replace('(void *)(uintptr_t)(0x44000000+MD_TEXTURE_BASE+(md_raw_image?0:1-md_front)*MD_TEXTURE_BYTES)', '(void *)(xv_ram+MD_TEXTURE_BASE+(1-md_front)*MD_TEXTURE_BYTES)')
replace('sceKernelDcacheWritebackRange(md_fade_image,MD_TEXTURE_BYTES);', 'sceKernelDcacheWritebackRange(md_fade_image,MD_TEXTURE_BYTES);xv_native_texture(md_fade_image);')
replace('static void md_fade_clear(void) {free(md_fade_image);', 'static void md_fade_clear(void) {xv_native_texture(NULL);free(md_fade_image);')
# Xbox presentation always uses the 720x480 theme coordinate space. The SDL
# adapter maps only the selected viewport to the current physical resolution.
replace('int left = fullscreen ? 0 : tv ? TV_LEFT_X : LCD_LEFT_X;', 'int left=0;')
replace('int top = fullscreen ? 0 : tv ? TV_LEFT_Y : LCD_LEFT_Y;', 'int top=0;')
replace('int right = fullscreen ? (tv ? 720 : 480) : tv ? TV_LEFT_R : LCD_LEFT_R;', 'int right=xv_width;')
replace('int bottom = fullscreen ? (tv ? 480 : 272) : tv ? TV_LEFT_B : LCD_LEFT_B;', 'int bottom=xv_height;')
replace('md_target(0, tv ? 768 : 512, tv ? 720 : 480, tv ? 480 : 272);', 'md_target(0,768,720,480);')
replace('md_next = finished + (cost > 25000ULL ? cost*2 : 50000ULL);', '(void)cost; md_next=now+50000ULL; /* Xbox: start-to-start cap; audio serviced cooperatively. */')
source+='\nint xbox_cave_phase(void){return cave_scene?cave_scene->game.phase:CAVE_GAME_OFF;}\n'
(out / 'visual_effects.c').write_text('/* Generated by tools/visual_adapter.py. */\n'+source)
game = (psp / 'cave_game_gu.h').read_text().replace('ms0:/PSP/SYSTEM/PSPStreamer-flight-a.dat', 'D:\\\\flight-a.dat').replace('ms0:/PSP/SYSTEM/PSPStreamer-flight-b.dat', 'D:\\\\flight-b.dat')
old='snprintf(text,sizeof(text),"%s %.1f / 5s",cave_hud_labels[8],g->exit_hold);'
if game.count(old)!=1:raise SystemExit('Xbox exit timer adapter needs review')
game=game.replace(old,'unsigned tenths=(unsigned)(fmin(5.0,fmax(0.0,g->exit_hold))*10); snprintf(text,sizeof(text),"%s %u.%u / 5s",cave_hud_labels[8],tenths/10,tenths%10);')
(out / 'cave_game_gu.h').write_text(game)
# Keep all Xbox translation units on the same extended CaveScene ABI. These
# headers are generated, never edits to the working PSP source/header tree.
for name,old,new in [('cave_visual.h','CAVE_AHEAD=16','CAVE_AHEAD=20'),
                     ('cave_paths.h','CAVE_PATH_CACHE=22','CAVE_PATH_CACHE=26')]:
    header=(psp/name).read_text()
    if header.count(old)!=1:raise SystemExit('Xbox cave horizon adapter needs review: '+name)
    (out/name).write_text(header.replace(old,new))
logo = (psp / 'assets/monkey-flight-logo.raw').read_bytes()
values = struct.unpack('<'+'H'*(len(logo)//2), logo)
(out / 'visual_logo.c').write_text('/* Generated from the existing Monkey logo asset. */\nconst unsigned short monkey_flight_logo[]={\n'+',\n'.join(','.join(str(x) for x in values[i:i+24]) for i in range(0,len(values),24))+'\n};\n')
