/* Deutsche PSP-Oberflächentexte.  Jede ID ist absichtlich explizit,
 * damit Übersetzungen unabhängig von der Reihenfolge bearbeitet werden können. */
static const char *const lang_de[TXT_COUNT] = {
    /* Bebilderte Hilfe; Seitentexte stehen in help_de.h. */
    [TXT_HELP] = "HILFE",
    [TXT_HELP_OPEN] = "Hilfe - Tasten und Kurzanleitungen",
    [TXT_HELP_POSITION] = "Thema %d/%d   Seite %d/%d",
    [TXT_HELP_KEYS] = "GOLD: HIER GENUTZT",
    [TXT_HELP_NAV] = "L / R THEMA    HOCH / RUNTER SEITE",
    [TXT_HELP_BACK] = "O ZURÜCK - ÄNDERT KEINE EINSTELLUNGEN",

    /* Lokale Bibliothek und Übertragungsstatus. */
    [TXT_LOCAL_STORAGE] = "LOKALER SPEICHER",
    [TXT_DOWNLOADS] = "SERVER-AUFTRÄGE",
    [TXT_CONVERTING] = "Warten / Server konvertiert",
    [TXT_DOWNLOADING] = "Übertragung auf Memory Stick",
    [TXT_VERIFYING] = "SHA256-Prüfsumme prüfen",
    [TXT_DOWNLOAD_STOPPING] = "Übertragung wird beendet...",
    [TXT_DOWNLOAD_ETA] = "Restdauer: %u Sekunden",
    [TXT_DOWNLOAD_CANCEL] = "O DOWNLOAD STOPPEN (AUFTRAG BLEIBT)",
    [TXT_DOWNLOAD_BACK] = "X / O ZURÜCK",
    [TXT_DOWNLOAD_RETRY] = "Unterbrochen - erneut wählen",
    [TXT_DOWNLOAD_SPACE] = "Zu wenig freier Memory-Stick-Speicher",
    [TXT_DOWNLOAD_DELETE] = "Diesen lokalen Download löschen?",
    [TXT_DOWNLOAD_CONFIRM] = "X LÖSCHEN   O BEHALTEN",
    [TXT_DOWNLOAD_QUEUE_HELP] = "X LADEN  [] LOKAL  SELECT HILFE  O ZURÜCK",
    [TXT_DOWNLOAD_LOCAL_HELP] = "X SPIELEN  [] LISTE  SELECT HILFE  O ZURÜCK",
    [TXT_PLAY_MODE] = "Wiedergabe",
    [TXT_STREAM_MODE] = "Streaming",
    [TXT_DOWNLOAD_MODE] = "Erst laden, dann abspielen",
    [TXT_DOWNLOAD_PROFILE] = "LCD/TV-Profil passt nicht",
    [TXT_DOWNLOAD_LCD_FILE] = "Datei: LCD (480 x 272)",
    [TXT_DOWNLOAD_TV_FILE] = "Datei: TV (720 x 480)",
    [TXT_DOWNLOAD_LCD_HELP] = "TV-Kabel abziehen oder TV-Version laden",
    [TXT_DOWNLOAD_TV_HELP] = "Component-TV verbinden oder LCD-Version laden",

    /* Allgemeine Einstellungen und Texteingabe. */
    [TXT_SETTINGS] = "EINSTELLUNGEN",
    [TXT_SETTINGS_HELP] = "HOCH/RUNTER WAHL   LINKS/RECHTS ÄNDERN",
    [TXT_SETTINGS_SAVED] = "Einstellungen gespeichert",
    [TXT_SETTINGS_FAILED] = "Speichern fehlgeschlagen; verworfen",
    [TXT_SETTINGS_HINT] = "SELECT: EINSTELLUNGEN",
    [TXT_SETTINGS_SAVE_HELP] = "START SPEICHERN   O ZURÜCK   X TEXT / ZAHL",
    [TXT_SETTINGS_ON] = "Ein",
    [TXT_INVALID_SETTING] = "Ungültiger Wert",
    [TXT_KEYBOARD_HELP] = "X ZEICHEN  L LÖSCHEN  R LEER  START OK  O ZURÜCK",

    [TXT_SETTINGS_HOST] = "Servername",
    [TXT_SETTINGS_PORT] = "Serverport",
    [TXT_SETTINGS_PASSWORD] = "Passwort",
    [TXT_SETTINGS_HTTPS] = "HTTPS",
    [TXT_SETTINGS_LANGUAGE] = "Sprache",
    [TXT_SETTINGS_TV] = "TV-Menü beim Start",
    [TXT_SETTINGS_CPU_MUSIC] = "Spektrum-CPU",
    [TXT_CPU_REQUIRED] = "Braucht StreamerOC: enabled=1, app_control=1",
    [TXT_CPU_ERROR] = "Taktanfrage gescheitert: %08X; Plugin-INI prüfen",
    [TXT_CPU_READY] = "Plugin bereit. OC-Limit: Plugin-INI. START speichert.",
    [TXT_SETTINGS_CPU_MILKDROP] = "MilkDrop-CPU",
    [TXT_SETTINGS_CPU_IDLE] = "Medienauswahl-CPU",
    [TXT_SETTINGS_CPU_VIDEO] = "Video-CPU (Plugin)",
    [TXT_SETTINGS_SCREEN] = "LCD-Ruhemodus",
    [TXT_SETTINGS_OC] = "StreamerOC-Plugin",

    [TXT_OC_TITLE] = "STREAMEROC EINSTELLUNGEN",
    [TXT_OC_ENABLED] = "Aktiviert",
    [TXT_OC_TARGET] = "Zieltakt",
    [TXT_OC_ENFORCE] = "Takt erzwingen",
    [TXT_OC_UNLIMITED] = "Unbegrenzt erzwingen",
    [TXT_OC_APP_CONTROL] = "App-Steuerung",
    [TXT_OC_REPORT] = "Protokoll schreiben",
    [TXT_OC_OVERLAY] = "Overlay",
    [TXT_OC_WARNING] = "Nur auf dieser PSP bereits getestete Taktraten!",
    [TXT_OC_HELP] = "START SPEICHERN: AB NÄCHSTEM APP-START   O ZURÜCK",
    [TXT_OC_SAVED] = "Plugin gespeichert; ab nächstem App-Start",
    [TXT_OC_READ_FAILED] = "Plugin-INI nicht sicher lesbar. O ZURÜCK",

    [TXT_SCREEN_AWAKE] = "Wach halten",
    [TXT_SCREEN_MUSIC] = "Auto: nur Musik",
    [TXT_SCREEN_AUTO] = "Auto: immer",
    [TXT_OUTPUT_LCD] = "Menü auf LCD wechseln [X]",
    [TXT_OUTPUT_TV] = "Menü auf TV wechseln [X]",
    [TXT_OUTPUT_FAILED] = "Komponentenkabel / TV prüfen: %08X",
    [TXT_OUTPUT_ON_LCD] = "Menü: LCD; Video folgt Kabel",
    [TXT_OUTPUT_ON_TV] = "Menü: TV",
    [TXT_SETTINGS_AUDIO] = "Tonspur",
    [TXT_SETTINGS_SUBTITLE] = "Untertitelspur",
    [TXT_SETTINGS_QUALITY] = "Tonqualität",
    [TXT_SETTINGS_FPS] = "Video-fps",
    [TXT_SETTINGS_VOLUME] = "Lautstärke",
    [TXT_SETTINGS_SHUFFLE] = "Zufallswiedergabe",
    [TXT_SETTINGS_PRESET] = "Preset-Datei",
    [TXT_SETTINGS_AUTO] = "Preset-Modus",
    [TXT_SETTINGS_SECONDS] = "Preset-Sekunden",
    [TXT_SETTINGS_FADE] = "Überblendung ms",
    [TXT_SETTINGS_DEBUG] = "Debug-Diagnose",
    [TXT_MUSIC_FINISHED] = "Musik beendet",
    [TXT_VIDEO_FINISHED] = "Video beendet",

    [TXT_TLS_FIRST] = "HTTPS-Zertifikat gespeichert",
    [TXT_TLS_CHANGED] = "HTTPS-Zertifikat geändert!",
    [TXT_TLS_SAVE_FAILED] = "HTTPS-Zertifikat nicht gespeichert",
    [TXT_FRAME_RATE] = "Bildrate",
    [TXT_PRESETS] = "MILKDROP PRESETS",
    [TXT_PRESET_CONTROLS] = "HOCH/RUNTER  L/R SEITE  X WAHL  O ZURÜCK",
    [TXT_PRESET_LIMIT] = "Max. 128",
    [TXT_PRESET_AUTO_STATUS] = "Auto: %s | %ds",
    [TXT_PRESET_AUTO_HELP] = "QUADRAT: MODUS   DREIECK: ZEIT",
    [TXT_PRESET_AUTO_OFF] = "Aus",
    [TXT_PRESET_AUTO_ORDER] = "Reihe",
    [TXT_PRESET_AUTO_RANDOM] = "Zufall",
    [TXT_PRESET_AUTO_RATED] = "Gewichtet",
    /* Vollbild-Steuerung */
    [TXT_TRANSPORT_PAUSE] = "Pause",
    [TXT_TRANSPORT_RESUME] = "Weiter",

    /* Eigene Visualisierung: darunter folgen Zeile und Feldname. */
    [TXT_PRESET_MISSING] = "Preset-Datei fehlt",
    [TXT_PRESET_INVALID] = "Ungültiger Preset-Wert",
    [TXT_PRESET_UNSUPPORTED] = "Preset-Feld nicht unterstützt",
    [TXT_PRESET_IO] = "Preset nicht lesbar",

    /* Native TV sidebar */
    [TXT_TV_SAVED_LINE1] = "Für nächste",
    [TXT_TV_SAVED_LINE2] = "Wiedergabe",
    [TXT_TV_SAVED_LINE3] = "gemerkt.",

    [TXT_TV_VOLUME] = "LAUTSTÄRKE\n%d %%",


    /* Library and loading panels */
    [TXT_MEDIA_LIBRARY] = "MEDIATHEK",
    [TXT_PREPARING_MEDIA] = "MEDIEN VORBEREITEN",
    [TXT_READING_MEDIA] = "MEDIENINFORMATIONEN LESEN",
    [TXT_LOADING_TRACKS] = "Audiospuren und Untertitel werden geladen...",
    [TXT_PREPARING_SUBTITLES] = "Untertitel werden vorbereitet...",
    [TXT_PREPARATION_WAIT] = "%u s   O ABBRECHEN",
    [TXT_SOURCE_WAKING] = "Die Quelle wird eventuell über SMB aufgeweckt.",
    [TXT_PLEASE_WAIT] = "BITTE WARTEN",
    [TXT_NO_VIDEO] = "Kein Video",
    [TXT_STREAM_HAS] = "Stream wurde",
    [TXT_STARTED] = "gestartet",
    [TXT_LIBRARY] = "BIBLIOTHEK",
    [TXT_NO_ENTRIES] = "Keine Einträge -- [] neu laden",
    [TXT_SELECTED] = "AUSGEWÄHLT",
    [TXT_WAITING] = "Warten...",
    [TXT_FOLDER] = "ORDNER",
    [TXT_MUSIC] = "MUSIK",
    [TXT_VIDEO] = "VIDEO",
    [TXT_ENTRIES] = "%d Einträge",
    [TXT_PROFILE] = "Profil %d",
    [TXT_AVC_READY] = "AVC BEREIT",
    [TXT_AVC_ERROR] = "AVC FEHLER",

    /* File information */
    [TXT_FILE_DETAILS] = "DATEIINFORMATIONEN",
    [TXT_MUSIC_STREAM] = "MUSIKSTREAM",
    [TXT_VIDEO_STREAM] = "H.264 VIDEO",
    [TXT_DURATION] = "DAUER: %d:%02d",
    [TXT_DURATION_UNKNOWN] = "DAUER: UNBEKANNT",
    [TXT_AUDIO_TRACKS] = "AUDIOSPUREN: %d",
    [TXT_SUBTITLE_TRACKS] = "UNTERTITEL: %d",
    [TXT_STREAMS] = "SPUREN",
    [TXT_NO_TRACKS] = "Keine Spuren.",

    /* Playback setup */
    [TXT_STREAM_OPTIONS] = "STREAM-OPTIONEN",
    [TXT_QUALITY] = "QUALITÄT",
    [TXT_SAVED_FOR] = "Gespeichert für",
    [TXT_NEXT_MUSIC] = "nächsten Musik-",
    [TXT_STREAM_BANG] = "stream!",
    [TXT_PLAY_ORDER] = "WIEDERGABEFOLGE",
    [TXT_SEQUENTIAL] = "REIHENFOLGE",
    [TXT_SHUFFLE] = "ZUFALL",
    [TXT_AUDIO_SUB] = "AUDIO & UNTERT.",
    [TXT_NEXT_PLAY] = "nächste Wieder-",
    [TXT_BACK] = "gabe",
    [TXT_AUDIO_LABEL] = "AUDIO: %s%s%s",
    [TXT_SUBS_LABEL] = "UT:     %s%s%s",
    [TXT_OFF] = "Aus",
    [TXT_NOT_DETECTED] = "nicht erkannt",

    /* Music playback */
    [TXT_NOW_PLAYING] = "WIRD ABGESPIELT",
    [TXT_VOLUME_LINE] = "MP3  %d%% LAUTSTÄRKE  SELECT PAUSE",
    [TXT_FULLSCREEN_MUSIC] = "MUSIK // %.48s",
    [TXT_MUSIC_CONTROLS] = "SELECT PAUSE  START STOPP  O PRESETS",
    [TXT_MUSIC_SETUP_CONTROLS] = "X START   O ZURÜCK   [] HILFE",
    [TXT_VIDEO_SETUP_CONTROLS] = "X START   O ZURÜCK   [] HILFE",
    [TXT_LIBRARY_CONTROLS] = "X ÖFFNEN   O LOKAL   SELECT EINSTELLUNGEN/HILFE",
    [TXT_INFO_CONTROLS] = "O / TRIANGLE ZURÜCK     X ZUR BIBLIOTHEK",

    /* Status messages */
    [TXT_CONNECTING_WIFI] = "WLAN verbindet (O: Abbruch)",
    [TXT_WIFI_NOT_READY] = "WLAN aus - Quadrat: verbinden",
    [TXT_LOADING_LIBRARY] = "Bibliothek wird geladen ...",
    [TXT_LIBRARY_ATTEMPT] = "Bibliothek: Versuch %d/%d, %us [O]",
    [TXT_LIBRARY_CANCELLED] = "Laden abgebrochen. Quadrat: neu laden",
    [TXT_NETWORK_STOPPING] = "Netzwerkanfrage wird beendet",
    [TXT_SERVER_ERROR] = "Serverfehler: %08X",
    [TXT_NETWORK_FAILED] = "%s fehlgeschlagen: %08X",
    [TXT_RESUMING] = "Wiedergabe ab %d s ...",
    [TXT_WIFI_RETRY] = "WLAN nicht bereit - X erneut drücken",
    [TXT_STARTING_MUSIC] = "Musikstream wird gestartet",
    [TXT_STARTING_VIDEO] = "H.264-Video startet",
    [TXT_INTERRUPTED] = "WLAN unterbrochen. WLAN verbinden, X zum Fortsetzen.",
    [TXT_MUSIC_ENDED] = "Musik beendet | Audio %d",
    [TXT_VIDEO_ENDED] = "Video beendet: %d Frames",
    [TXT_NEXT_EPISODE] = "Nächste Episode: %.58s",
    [TXT_NEXT_TRACK] = "Nächster Titel: %.58s",

    [TXT_RADIO] = "Internetradio",
    [TXT_RADIO_PAUSED] = "Radiopause SELECT: live START: Stopp",
    [TXT_RADIO_RECONNECT] = "Radio in 5s verbinden - START: Stopp"};
