#ifndef PSP_STREAMER_LANGUAGE_H
#define PSP_STREAMER_LANGUAGE_H

typedef enum {
    TXT_MEDIA_LIBRARY, TXT_PREPARING_MEDIA, TXT_READING_MEDIA,
    TXT_LOADING_TRACKS, TXT_SOURCE_WAKING, TXT_PLEASE_WAIT,
    TXT_PREPARING_SUBTITLES, TXT_PREPARATION_WAIT,
    TXT_NO_VIDEO, TXT_STREAM_HAS, TXT_STARTED,
    TXT_LIBRARY, TXT_NO_ENTRIES, TXT_SELECTED, TXT_WAITING,
    TXT_FOLDER, TXT_MUSIC, TXT_VIDEO, TXT_ENTRIES, TXT_PROFILE,
    TXT_AVC_READY, TXT_AVC_ERROR, TXT_FILE_DETAILS, TXT_MUSIC_STREAM,
    TXT_VIDEO_STREAM, TXT_DURATION, TXT_DURATION_UNKNOWN, TXT_AUDIO_TRACKS,
    TXT_SUBTITLE_TRACKS, TXT_STREAMS, TXT_NO_TRACKS, TXT_STREAM_OPTIONS,
    TXT_QUALITY, TXT_SAVED_FOR, TXT_NEXT_MUSIC, TXT_STREAM_BANG,
    TXT_PLAY_ORDER, TXT_SEQUENTIAL, TXT_SHUFFLE,
    TXT_AUDIO_SUB, TXT_NEXT_PLAY, TXT_BACK, TXT_AUDIO_LABEL,
    TXT_SUBS_LABEL, TXT_OFF, TXT_NOT_DETECTED, TXT_NOW_PLAYING,
    TXT_VOLUME_LINE, TXT_FULLSCREEN_MUSIC, TXT_MUSIC_CONTROLS,
    TXT_MUSIC_SETUP_CONTROLS, TXT_VIDEO_SETUP_CONTROLS, TXT_LIBRARY_CONTROLS,
    TXT_INFO_CONTROLS, TXT_CONNECTING_WIFI, TXT_WIFI_NOT_READY,
    TXT_LOADING_LIBRARY, TXT_LIBRARY_CANCELLED, TXT_NETWORK_STOPPING, TXT_SERVER_ERROR, TXT_NETWORK_FAILED,
    TXT_RESUMING, TXT_WIFI_RETRY, TXT_STARTING_MUSIC, TXT_STARTING_VIDEO,
    TXT_INTERRUPTED, TXT_MUSIC_ENDED, TXT_VIDEO_ENDED, TXT_NEXT_EPISODE, TXT_NEXT_TRACK,
    TXT_TV_SAVED_LINE1, TXT_TV_SAVED_LINE2, TXT_TV_SAVED_LINE3, TXT_TV_VOLUME,
    TXT_PRESET_MISSING, TXT_PRESET_INVALID, TXT_PRESET_UNSUPPORTED, TXT_PRESET_IO,
    TXT_TRANSPORT_PAUSE, TXT_TRANSPORT_RESUME,
    TXT_FRAME_RATE,
    TXT_PRESETS, TXT_PRESET_CONTROLS, TXT_PRESET_LIMIT,
    TXT_PRESET_AUTO_STATUS, TXT_PRESET_AUTO_HELP,
    TXT_PRESET_AUTO_OFF, TXT_PRESET_AUTO_ORDER, TXT_PRESET_AUTO_RANDOM, TXT_PRESET_AUTO_RATED,
    TXT_SETTINGS, TXT_SETTINGS_HELP, TXT_SETTINGS_SAVED, TXT_SETTINGS_FAILED,
    TXT_SETTINGS_HOST, TXT_SETTINGS_PORT, TXT_SETTINGS_PASSWORD, TXT_SETTINGS_HTTPS,
    TXT_SETTINGS_LANGUAGE, TXT_SETTINGS_TV, TXT_SETTINGS_AUDIO, TXT_SETTINGS_SUBTITLE,
    TXT_SETTINGS_QUALITY, TXT_SETTINGS_FPS, TXT_SETTINGS_VOLUME, TXT_SETTINGS_SHUFFLE,
    TXT_SETTINGS_PRESET, TXT_SETTINGS_AUTO, TXT_SETTINGS_SECONDS, TXT_SETTINGS_FADE,
    TXT_SETTINGS_DEBUG,
    TXT_SETTINGS_CPU_MUSIC, TXT_SETTINGS_CPU_MILKDROP, TXT_SETTINGS_CPU_VIDEO, TXT_SETTINGS_CPU_IDLE, TXT_SETTINGS_SCREEN, TXT_SETTINGS_OC,
    TXT_OC_TITLE, TXT_OC_ENABLED, TXT_OC_TARGET, TXT_OC_ENFORCE, TXT_OC_UNLIMITED,
    TXT_OC_APP_CONTROL, TXT_OC_REPORT, TXT_OC_OVERLAY, TXT_OC_WARNING, TXT_OC_HELP, TXT_OC_SAVED, TXT_OC_READ_FAILED,
    TXT_MUSIC_FINISHED, TXT_VIDEO_FINISHED,
    TXT_KEYBOARD_HELP, TXT_INVALID_SETTING, TXT_TLS_FIRST, TXT_TLS_CHANGED, TXT_TLS_SAVE_FAILED,
    TXT_SETTINGS_HINT, TXT_SETTINGS_SAVE_HELP, TXT_SETTINGS_ON,
    TXT_LOCAL_STORAGE, TXT_DOWNLOADS, TXT_CONVERTING, TXT_DOWNLOADING, TXT_VERIFYING,
    TXT_DOWNLOAD_STOPPING, TXT_DOWNLOAD_ETA, TXT_DOWNLOAD_CANCEL, TXT_DOWNLOAD_BACK,
    TXT_DOWNLOAD_RETRY, TXT_DOWNLOAD_SPACE, TXT_DOWNLOAD_DELETE, TXT_DOWNLOAD_CONFIRM,
    TXT_DOWNLOAD_QUEUE_HELP, TXT_DOWNLOAD_LOCAL_HELP, TXT_PLAY_MODE, TXT_STREAM_MODE,
    TXT_DOWNLOAD_MODE, TXT_DOWNLOAD_PROFILE,
    TXT_DOWNLOAD_LCD_FILE, TXT_DOWNLOAD_TV_FILE,
    TXT_DOWNLOAD_LCD_HELP, TXT_DOWNLOAD_TV_HELP,
    TXT_RADIO, TXT_RADIO_PAUSED, TXT_RADIO_RECONNECT,
    TXT_HELP, TXT_HELP_OPEN, TXT_HELP_POSITION, TXT_HELP_KEYS, TXT_HELP_NAV, TXT_HELP_BACK,
    TXT_OUTPUT_LCD, TXT_OUTPUT_TV, TXT_OUTPUT_FAILED, TXT_OUTPUT_ON_LCD, TXT_OUTPUT_ON_TV,
    TXT_LIBRARY_ATTEMPT,
    TXT_SCREEN_AWAKE, TXT_SCREEN_MUSIC, TXT_SCREEN_AUTO,
    TXT_CPU_REQUIRED, TXT_CPU_ERROR, TXT_CPU_READY,
    TXT_COUNT
} TextId;

const char *tr(TextId id);
void language_set_code(const char *code);
const char *language_code(void);

#endif
