/* Deutsche PSP-Oberflächentexte.  Jede ID ist absichtlich explizit,
 * damit Übersetzungen unabhängig von der Reihenfolge bearbeitet werden können. */
static const char *const lang_de[TXT_COUNT] = {
    /* Komfort, Lesezeichen, Profile und Reisevorbereitung. */
    [TXT_COMFORT] = "Schnellzugriff / Wiedergabegrenzen",
    [TXT_FAVORITES] = "Favoriten",
    [TXT_RECENT] = "Zuletzt abgespielt",
    [TXT_FAVORITE_TOGGLE] = "Auswahl als Favorit umschalten",
    [TXT_SERVER_PROFILES] = "Serverprofile",
    [TXT_TIMER] = "Stopp in: %d Min (0 = aus)",
    [TXT_STOP_AFTER] = "Stopp nach: %d Dateien (0 = aus)",
    [TXT_COMFORT_HELP] = "X ÖFFNEN   LINKS/RECHTS ÄNDERN   O ZURÜCK",
    [TXT_SHORTCUT_HELP] = "X ÖFFNEN   DREIECK ENTFERNEN   O ZURÜCK",
    [TXT_PROFILE_HELP] = "X NUTZEN   [] SICHERN   DREIECK LÖSCHEN",
    [TXT_PROFILE_NAME] = "Profilname",
    [TXT_EMPTY_SLOT] = "Freier Speicherplatz",
    [TXT_RESUME_QUESTION] = "Bei %d:%02d fortsetzen?",
    [TXT_RESUME_HELP] = "X FORTSETZEN   [] NEUSTART   O ZURÜCK",
    [TXT_TRAVEL] = "Reise / Speicherübersicht",
    [TXT_TRAVEL_COUNTS] = "Vollständig: %d   Unvollständig: %d",
    [TXT_TRAVEL_SPACE] = "Frei: %.1f MiB",
    [TXT_TRAVEL_SIZE] = "Auswahl benötigt noch: %.1f MiB",
    [TXT_TRAVEL_HELP] = "X ÜBERTRAGEN   O ABBRECHEN",
    [TXT_STORAGE_FULL] = "Favoriten voll / Speichern fehlgeschlagen",
    [TXT_COMFORT_SAVED] = "Gespeichert",
    [TXT_TIMER_HINT] = "Nur diese Sitzung; Timer zählt auch Pausen.",
    [TXT_PROFILE_SAVED] = "CFG vor dem Speichern eines Profils sichern.",

    /* Bebilderte Hilfe; Seitentexte stehen in help_de.h. */
    [TXT_HELP] = "HILFE",
    [TXT_HELP_OPEN] = "Hilfe - Tasten und Kurzanleitungen",
    [TXT_HELP_POSITION] = "Thema %d/%d   Seite %d/%d",
    [TXT_HELP_KEYS] = "GOLD: HIER GENUTZT",
    [TXT_HELP_NAV] = "L / R THEMA    HOCH / RUNTER SEITE",
    [TXT_HELP_BACK] = "O ZURÜCK - ÄNDERT KEINE EINSTELLUNGEN",

    /* Lokale Bibliothek und Übertragungsstatus. */
    [TXT_LOCAL_STORAGE] = "LOKALER SPEICHER",
    [TXT_DOWNLOADS] = "SERVER-AUFTRÄGE",
    [TXT_CONVERTING] = "Server konvertiert",
    [TXT_DOWNLOAD_QUEUED] = "In Server-Warteschlange",
    [TXT_DOWNLOADING] = "Übertragung auf Memory Stick",
    [TXT_VERIFYING] = "SHA256-Prüfsumme prüfen",
    [TXT_DOWNLOAD_STOPPING] = "Übertragung wird beendet...",
    [TXT_DOWNLOAD_ETA] = "Restdauer: %u Sekunden",
    [TXT_DOWNLOAD_CANCEL] = "O DOWNLOAD STOPPEN (AUFTRAG BLEIBT)",
    [TXT_DOWNLOAD_BACK] = "X / O ZURÜCK",
    [TXT_DOWNLOAD_RETRY] = "Unterbrochen - erneut wählen",
    [TXT_DOWNLOAD_SPACE] = "Zu wenig freier Memory-Stick-Speicher",
    [TXT_DOWNLOAD_DELETE] = "Diesen lokalen Download löschen?",
    [TXT_DOWNLOAD_CONFIRM] = "X LÖSCHEN   O BEHALTEN",
    [TXT_DOWNLOAD_QUEUE_HELP] = "X LADEN  [] LOKAL  SELECT HILFE  O ZURÜCK",
    [TXT_DOWNLOAD_LOCAL_HELP] = "X SPIELEN  [] LISTE  SELECT HILFE  O ZURÜCK",
    [TXT_PLAY_MODE] = "Wiedergabe",
    [TXT_STREAM_MODE] = "Streaming",
    [TXT_DOWNLOAD_MODE] = "Erst laden, dann abspielen",
    [TXT_DOWNLOAD_PROFILE] = "LCD/TV-Profil passt nicht",
    [TXT_DOWNLOAD_LCD_FILE] = "Datei: LCD (480 x 272)",
    [TXT_DOWNLOAD_TV_FILE] = "Datei: TV (720 x 480)",
    [TXT_DOWNLOAD_LCD_HELP] = "TV-Kabel abziehen oder TV-Version laden",
    [TXT_DOWNLOAD_TV_HELP] = "Component-TV verbinden oder LCD-Version laden",

    /* Allgemeine Einstellungen und Texteingabe. */
    [TXT_SETTINGS] = "EINSTELLUNGEN",
    [TXT_SETTINGS_HELP] = "HOCH/RUNTER WAHL   LINKS/RECHTS ÄNDERN",
    [TXT_SETTINGS_SAVED] = "Einstellungen gespeichert",
    [TXT_SETTINGS_FAILED] = "Speichern fehlgeschlagen; verworfen",
    [TXT_SETTINGS_HINT] = "SELECT: EINSTELLUNGEN",
    [TXT_SETTINGS_SAVE_HELP] = "START SPEICHERN   O ZURÜCK   X TEXT / ZAHL",
    [TXT_SETTINGS_ON] = "Ein",
    [TXT_INVALID_SETTING] = "Ungültiger Wert",
    [TXT_KEYBOARD_HELP] = "X ZEICHEN  L LÖSCHEN  R LEER  START OK  O ZURÜCK",

    [TXT_SETTINGS_HOST] = "Servername",
    [TXT_SETTINGS_PORT] = "Serverport",
    [TXT_SETTINGS_PASSWORD] = "Passwort",
    [TXT_SETTINGS_HTTPS] = "HTTPS",
    [TXT_SETTINGS_LANGUAGE] = "Sprache",
    [TXT_SETTINGS_TV] = "TV-Menü beim Start",
    [TXT_SETTINGS_CPU_MUSIC] = "Musik/Spektrum-CPU",
    [TXT_CPU_REQUIRED] = "Braucht StreamerOC: enabled=1, app_control=1",
    [TXT_CPU_ERROR] = "Taktanfrage gescheitert: %08X; Plugin-INI prüfen",
    [TXT_CPU_READY] = "Plugin bereit. OC-Limit: Plugin-INI. START speichert.",
    [TXT_SETTINGS_CPU_MILKDROP] = "MilkDrop/Monkey-CPU",
    [TXT_SETTINGS_CPU_IDLE] = "Medienauswahl-CPU",
    [TXT_SETTINGS_CPU_DOWNLOAD] = "Download/Prüfung-CPU",
    [TXT_SETTINGS_CPU_VIDEO] = "Video-CPU (Plugin)",
    [TXT_SETTINGS_SCREEN] = "LCD-Ruhemodus",
    [TXT_SETTINGS_RESOLUTION] = "MilkDrop-Auflösung",
    [TXT_SETTINGS_ANALYSIS] = "Musikanalyse",
    [TXT_SETTINGS_BANDS] = "FFT-Balken LCD",
    [TXT_SETTINGS_BANDS_TV] = "FFT-Balken TV",
    [TXT_SETTINGS_SPECTRUM_GAIN] = "FFT-Pegel (dB)",
    [TXT_SETTINGS_SPECTRUM_STYLE] = "Spektrumfarben",
    [TXT_SETTINGS_SPECTRUM_SEGMENTS] = "LED-Segmente",
    [TXT_SETTINGS_SPECTRUM_PEAK] = "Spitzen halten",
    [TXT_SETTINGS_SPECTRUM_LEDS] = "LEDs pro Balken",

    [TXT_SPECTRUM_ORIGINAL] = "Original",
    [TXT_SPECTRUM_RAINBOW] = "Regenbogen",
    [TXT_SPECTRUM_VU] = "Klassisch VU",
    [TXT_SPECTRUM_ICE] = "Eis",
    [TXT_SPECTRUM_FIRE] = "Feuer",

    [TXT_ANALYSIS_LEGACY] = "Sparsam (12)",
    [TXT_ANALYSIS_FFT] = "Desktop FFT",
    [TXT_SETTINGS_OC] = "Plugins",
    [TXT_PLUGINS] = "Plugins",
    [TXT_CAVE_RUMBLE_MUSIC] = "Musik-Vibration (%)",
    [TXT_CAVE_RUMBLE_GAME] = "Treffer-Vibration (%)",
    [TXT_PLUGIN_GLOBAL] = "Grundeinstellungen",
    [TXT_PLUGIN_RULES] = "Titel- / Pfadregeln",
    [TXT_PLUGIN_FILTERS] = "Pfadfilter",
    [TXT_PLUGIN_ADD_TITLE] = "Titel-ID hinzufügen",
    [TXT_PLUGIN_ADD_PATH] = "Exakten Pfad hinzufügen",
    [TXT_PLUGIN_ALLOW] = "Erlaubten Pfad hinzufügen",
    [TXT_PLUGIN_EXCLUDE] = "Ausgeschlossenen Pfad hinzufügen",
    [TXT_PLUGIN_INHERIT] = "Global",
    [TXT_PLUGIN_ALWAYS] = "Overlay dauerhaft",
    [TXT_PLUGIN_HOME] = "PS/Home-Kombination",
    [TXT_PLUGIN_VSH] = "XMB-Steuerung",
    [TXT_PLUGIN_POPS] = "PS1-Steuerung",
    [TXT_PLUGIN_RUMBLE] = "PS1-Vibration",
    [TXT_HR_TITLE] = "Spiel-Vibration",
    [TXT_HR_ADDRESS] = "Lebensadresse",
    [TXT_HR_TYPE] = "Datentyp",
    [TXT_HR_POINTER] = "Zeiger lesen",
    [TXT_HR_OFFSET] = "Zeiger-Offset",
    [TXT_HR_MIN] = "Minimum Leben",
    [TXT_HR_MAX] = "Maximum Leben",
    [TXT_HR_STRENGTH] = "Max. Motor (0-255)",
    [TXT_HR_DURATION] = "Fester Impuls (ms)",
    [TXT_HR_COOLDOWN] = "Sperrzeit (ms)",
    [TXT_HR_GATE] = "Kampfstatus-Adresse",
    [TXT_HR_GATE_VALUE] = "Kampfstatus-Wert",
    [TXT_HR_ADDRESS_HINT] = "X: volle PSP-Adresse, z.B. 0x088...",
    [TXT_HR_GATE_HINT] = "Optionaler uint32-Status; 0 = aus.",
    [TXT_HR_TYPE_HINT] = "Speichertyp, nicht Lebensbalkenlänge.",
    [TXT_HR_POINTER_HINT] = "Optionaler Zeiger; sonst AUS/0.",
    [TXT_HR_RANGE_HINT] = "Gültige Lebenswerte, keine Stärke.",
    [TXT_HR_COOLDOWN_HINT] = "Mindestabstand der Trefferimpulse.",
    [TXT_HR_DEFAULT_HINT] = "QUADRAT: Standard. Siehe RUMBLE.md.",
    [TXT_HI_CW] = "CWCheat-Zeile importieren",
    [TXT_HI_RETRO] = "RetroArch-Fund importieren",
    [TXT_HI_CW_INPUT] = "Eine _L-Schreibzeile (kein Skript)",
    [TXT_HI_RETRO_INPUT] = "PPSSPP-RAM-Offset (Hex)",
    [TXT_HI_TYPE] = "Typ: 1=u8 2=u16 3=u32 4=float",
    [TXT_HI_MAX] = "Volle Leben (dezimal; Wert prüfen)",
    [TXT_HI_DUPLICATE] = "Titel vorhanden; Profil bearbeiten.",
    [TXT_HI_REVIEW] = "Import AUS. Prüfen, aktivieren, sichern.",
    [TXT_HR_MODE] = "Rumble-Modus",
    [TXT_HR_PEAK] = "Schaden für Maximum",
    [TXT_HR_DURATION_MIN] = "Min. Impuls (ms)",
    [TXT_HR_DURATION_MAX] = "Max. Impuls (ms)",
    [TXT_HR_DYNAMIC_HINT] = "Schaden regelt Stärke und Dauer.",
    [TXT_HR_FIXED] = "Fest",
    [TXT_HR_DYNAMIC] = "Schadensabhängig",
    [TXT_PLUGIN_TV] = "Automatischer TV-Ausgang",
    [TXT_PLUGIN_METADATA] = "Name / Akkudaten",
    [TXT_PLUGIN_AUTOZOOM] = "Automatisches Vollbild",
    [TXT_PLUGIN_DELAY] = "Startverzögerung (s)",
    [TXT_PLUGIN_KEEP] = "Vollbild beibehalten",
    [TXT_PLUGIN_GUARD] = "VBlank-Kopierschutz",
    [TXT_PLUGIN_OFF] = "Aus",
    [TXT_PLUGIN_ON] = "An",
    [TXT_PLUGIN_POLL] = "Polling",
    [TXT_PLUGIN_HOOK] = "Bildwechsel-Hook",
    [TXT_PLUGIN_CONNECTED] = "Controller verbunden",
    [TXT_PLUGIN_START] = "Anwendungsstart",
    [TXT_PLUGIN_HELP] = "X: ändern  START: speichern  O: zurück",
    [TXT_PLUGIN_RULE_HELP] = "X: ändern  []: Name  /\\ zweimal: löschen",
    [TXT_PLUGIN_VALUES_HELP] = "Links/rechts: ändern  []: global  O: zurück",
    [TXT_PLUGIN_RESTART] = "Gespeichert. Spiel / XMB neu starten.",
    [TXT_PLUGIN_ERROR] = "INI-Fehler: Format, Größe oder Pfad.",
    [TXT_PLUGIN_CONFIRM] = "Zum Löschen erneut DREIECK drücken.",
    [TXT_PLUGIN_PATH_HINT] = "Exakter Startpfad; Titel-ID hat Vorrang.",
    [TXT_PLUGIN_MAIN_HINT] = "Startwerte; ARK-Einträge bleiben unverändert.",
    [TXT_PLUGIN_FILTER_HINT] = "Teilpfad: Groß/klein beachten; max. 8 je Typ.",

    [TXT_SETTINGS_STREAMMASTER] = "StreamMaster USB",
    [TXT_SETTINGS_TRANSPORT] = "Netzwerkweg",
    [TXT_TRANSPORT_RESTART] = "Speichern, dann App für Wechsel neu starten.",
    [TXT_SM_ATTACH] = "USB verbinden / erneut",
    [TXT_SM_INFO] = "Netzwerkstatus",
    [TXT_SM_SCAN] = "WLAN-Netze suchen",
    [TXT_SM_PROFILE] = "Profil (X: weiter)",
    [TXT_SM_AUTOMATIC] = "Netzwahl auto",
    [TXT_SM_DELETE] = "Profil löschen",
    [TXT_SM_EMPTY] = "Leer",
    [TXT_SM_DELETE_CONFIRM] = "Löschen: nochmals X",
    [TXT_SM_SSID] = "SSID",
    [TXT_SM_PASSWORD] = "WLAN-Passwort",
    [TXT_SM_DHCP] = "DHCP",
    [TXT_SM_AUTO_DNS] = "DNS über DHCP",
    [TXT_SM_IP] = "IPv4-Adresse",
    [TXT_SM_MASK] = "Subnetzmaske",
    [TXT_SM_GATEWAY] = "Gateway",
    [TXT_SM_DNS] = "DNS-Server",
    [TXT_SM_DNS2] = "Ersatz-DNS",
    [TXT_SM_SAVE] = "Auf Onju speichern + verbinden",
    [TXT_SM_CONNECT] = "WLAN neu verbinden",
    [TXT_SM_BENCH] = "USB-Übertragungstest",
    [TXT_SM_SERVER] = "Gespeicherten Server prüfen",
    [TXT_SM_BT] = "Bluetooth-Controller",
    [TXT_SM_BT_SCAN] = "Controller suchen",
    [TXT_SM_BT_DISCONNECT] = "Controller trennen",
    [TXT_SM_BT_FORGET] = "Gewähltes Gerät vergessen",
    [TXT_SM_BT_HELP] = "X: verbinden | Dreieck: vergessen | O: zurück",
    [TXT_SM_BT_STATE] = "Eingaben: %u | Fehler: %08X",
    [TXT_SM_BT_CONFIRM] = "Vergessen: nochmals X",
    [TXT_SM_BT_NONE] = "Kein USB-Bluetooth-Adapter",
    [TXT_SM_BT_STARTING] = "Bluetooth startet...",
    [TXT_SM_BT_READY] = "Bereit (USB-Bluetooth-Test)",
    [TXT_SM_BT_SCANNING] = "Controller werden gesucht...",
    [TXT_SM_BT_CONNECTING] = "Controller verbinden...",
    [TXT_SM_BT_CONNECTED] = "Controller verbunden",
    [TXT_SM_BT_ERROR] = "Bluetooth-Fehler",
    [TXT_SM_BT_OPTIONS] = "Tasten / Neuverbinden",
    [TXT_SM_BT_AUTO] = "Automatisch verbinden",
    [TXT_SM_BT_DEFAULTS] = "Standard-Tastenbelegung",
    [TXT_SM_BT_MAP_HELP] = "PSP: X: anlernen/ändern | Start: speichern | O: zurück",
    [TXT_SM_BT_WIZARD] = "Alle Tasten einrichten",
    [TXT_SM_BT_PRESS] = "Controller-Taste drücken für:",
    [TXT_SM_BT_RELEASE] = "Controller-Tasten loslassen",
    [TXT_SM_BT_CIRCLE_STICK] = "Gewünschten Stick im Kreis drehen",
    [TXT_SM_BT_CENTER_STICK] = "Danach zur Mitte loslassen",
    [TXT_SM_BT_LEARN_HELP] = "PSP: Quadrat: überspringen | O: abbrechen",
    [TXT_SM_BT_ANALOG] = "Analogstick",
    [TXT_SM_BT_INVERT_X] = "Analog X umkehren",
    [TXT_SM_BT_INVERT_Y] = "Analog Y umkehren",
    [TXT_SM_BT_NEED_CONNECTED] = "Zuerst Controller verbinden",
    [TXT_SM_BT_UP] = "Hoch",
    [TXT_SM_BT_RIGHT] = "Rechts",
    [TXT_SM_BT_DOWN] = "Runter",
    [TXT_SM_BT_LEFT] = "Links",
    [TXT_SM_BT_RAW] = "Gedrückte HID-Tasten: %04X",
    [TXT_SM_BT_SAVED_MARK] = "* = gespeicherter Controller",

    [TXT_SM_WAIT] = "Warte auf StreamMaster...",
    [TXT_SM_CANCEL] = "Kreis: abbrechen",
    [TXT_SM_HELP] = "Hoch/runter: wählen | X: öffnen | Kreis: zurück",
    [TXT_SM_RETAIN] = "Gespeichertes behalten",
    [TXT_SM_HIDDEN] = "********",
    [TXT_SM_ERROR] = "Fehler",
    [TXT_SM_TEST_ONLY] = "Hardwaretest; Wiedergabe weiter über PSP-WLAN",
    [TXT_SM_SAVED] = "Auf Onju gespeichert; Netzwerkstatus prüfen",
    [TXT_SM_NO_AP] = "Kein Netz gefunden; SSID manuell eingeben",
    [TXT_SM_IDLE] = "Getrennt",
    [TXT_SM_CONNECTING] = "Verbinden",
    [TXT_SM_READY] = "Verbunden",
    [TXT_SM_FAILED] = "WLAN-Fehler",

    [TXT_OC_TITLE] = "STREAMEROC EINSTELLUNGEN",
    [TXT_OC_ENABLED] = "Aktiviert",
    [TXT_OC_TARGET] = "Zieltakt",
    [TXT_OC_ENFORCE] = "Takt erzwingen",
    [TXT_OC_UNLIMITED] = "Unbegrenzt erzwingen",
    [TXT_OC_APP_CONTROL] = "App-Steuerung",
    [TXT_OC_REPORT] = "Protokoll schreiben",
    [TXT_OC_OVERLAY] = "Overlay",
    [TXT_OC_POLLING] = "1: bisherig",
    [TXT_OC_HOOK] = "2: Framebuffer-Hook",
    [TXT_OC_WARNING] = "Nur auf dieser PSP bereits getestete Taktraten!",
    [TXT_OC_HELP] = "START SPEICHERN: AB NÄCHSTEM APP-START   O ZURÜCK",
    [TXT_OC_SAVED] = "Plugin gespeichert; ab nächstem App-Start",
    [TXT_OC_READ_FAILED] = "Plugin-INI nicht sicher lesbar. O ZURÜCK",

    [TXT_SCREEN_AWAKE] = "Wach halten",
    [TXT_SCREEN_MUSIC] = "Auto: nur Musik",
    [TXT_SCREEN_AUTO] = "Auto: immer",
    [TXT_OUTPUT_LCD] = "Menü auf LCD wechseln [X]",
    [TXT_OUTPUT_TV] = "Menü auf TV wechseln [X]",
    [TXT_OUTPUT_FAILED] = "Komponentenkabel / TV prüfen: %08X",
    [TXT_OUTPUT_ON_LCD] = "Menü: LCD; Video folgt Kabel",
    [TXT_OUTPUT_ON_TV] = "Menü: TV",
    [TXT_SETTINGS_AUDIO] = "Tonspur",
    [TXT_SETTINGS_SUBTITLE] = "Untertitelspur",
    [TXT_SETTINGS_QUALITY] = "Tonqualität",
    [TXT_SETTINGS_FPS] = "Video-fps",
    [TXT_SETTINGS_VOLUME] = "Lautstärke",
    [TXT_SETTINGS_SHUFFLE] = "Zufallswiedergabe",
    [TXT_SETTINGS_PRESET] = "Preset-Datei",
    [TXT_SETTINGS_AUTO] = "Preset-Modus",
    [TXT_SETTINGS_SECONDS] = "Preset-Sekunden",
    [TXT_SETTINGS_FADE] = "Überblendung ms",
    [TXT_SETTINGS_DEBUG] = "Debug-Diagnose",
    [TXT_MUSIC_FINISHED] = "Musik beendet",
    [TXT_VIDEO_FINISHED] = "Video beendet",

    [TXT_TLS_FIRST] = "HTTPS-Zertifikat gespeichert",
    [TXT_TLS_CHANGED] = "HTTPS-Zertifikat geändert!",
    [TXT_TLS_SAVE_FAILED] = "HTTPS-Zertifikat nicht gespeichert",
    [TXT_FRAME_RATE] = "Bildrate",
    [TXT_PRESETS] = "MILKDROP PRESETS",
    [TXT_PRESET_CONTROLS] = "HOCH/RUNTER  L/R SEITE  X WAHL  O ZURÜCK",
    [TXT_PRESET_LIMIT] = "Max. 128",
    [TXT_PRESET_AUTO_STATUS] = "Auto: %s | %ds",
    [TXT_PRESET_AUTO_HELP] = "[]: MODUS /\\: ZEIT SELECT: OPTIONEN",
    [TXT_PRESET_AUTO_OFF] = "Aus",
    [TXT_PRESET_AUTO_ORDER] = "Reihe",
    [TXT_PRESET_AUTO_RANDOM] = "Zufall",
    [TXT_PRESET_AUTO_RATED] = "Gewichtet",
    /* Vollbild-Steuerung */
    [TXT_TRANSPORT_PAUSE] = "Pause",
    [TXT_TRANSPORT_RESUME] = "Weiter",

    /* Eigene Visualisierung: darunter folgen Zeile und Feldname. */
    [TXT_PRESET_MISSING] = "Preset-Datei fehlt",
    [TXT_PRESET_INVALID] = "Ungültiger Preset-Wert",
    [TXT_PRESET_UNSUPPORTED] = "Preset-Feld nicht unterstützt",
    [TXT_PRESET_IO] = "Preset nicht lesbar",

    /* Native TV sidebar */
    [TXT_TV_SAVED_LINE1] = "Für nächste",
    [TXT_TV_SAVED_LINE2] = "Wiedergabe",
    [TXT_TV_SAVED_LINE3] = "gemerkt.",

    [TXT_TV_VOLUME] = "LAUTSTÄRKE\n%d %%",


    /* Library and loading panels */
    [TXT_MEDIA_LIBRARY] = "MEDIATHEK",
    [TXT_PREPARING_MEDIA] = "MEDIEN VORBEREITEN",
    [TXT_READING_MEDIA] = "MEDIENINFORMATIONEN LESEN",
    [TXT_LOADING_TRACKS] = "Audiospuren und Untertitel werden geladen...",
    [TXT_PREPARING_SUBTITLES] = "Untertitel werden vorbereitet...",
    [TXT_PREPARATION_WAIT] = "%u s   O ABBRECHEN",
    [TXT_SOURCE_WAKING] = "Die Quelle wird eventuell über SMB aufgeweckt.",
    [TXT_PLEASE_WAIT] = "WARTEN...",
    [TXT_NO_VIDEO] = "Kein Video",
    [TXT_STREAM_HAS] = "wurde",
    [TXT_STARTED] = "gestartet",
    [TXT_LIBRARY] = "BIBLIOTHEK",
    [TXT_NO_ENTRIES] = "Keine Einträge -- [] neu laden",
    [TXT_SELECTED] = "AUSGEWÄHLT",
    [TXT_WAITING] = "Warten...",
    [TXT_FOLDER] = "ORDNER",
    [TXT_MUSIC] = "MUSIK",
    [TXT_VIDEO] = "VIDEO",
    [TXT_ENTRIES] = "%d Eintr",
    [TXT_PROFILE] = "Profil %d",
    [TXT_AVC_READY] = "AVC BEREIT",
    [TXT_AVC_ERROR] = "AVC FEHLER",

    /* File information */
    [TXT_FILE_DETAILS] = "DATEIINFORMATIONEN",
    [TXT_MUSIC_STREAM] = "MUSIKSTREAM",
    [TXT_VIDEO_STREAM] = "H.264 VIDEO",
    [TXT_DURATION] = "DAUER: %d:%02d",
    [TXT_DURATION_UNKNOWN] = "DAUER: UNBEKANNT",
    [TXT_AUDIO_TRACKS] = "AUDIOSPUREN: %d",
    [TXT_SUBTITLE_TRACKS] = "UNTERTITEL: %d",
    [TXT_STREAMS] = "SPUREN",
    [TXT_NO_TRACKS] = "Keine",

    /* Playback setup */
    [TXT_STREAM_OPTIONS] = "STREAM-OPTIONEN",
    [TXT_QUALITY] = "QUALITÄT",
    [TXT_SAVED_FOR] = "Gemerkt:",
    [TXT_NEXT_MUSIC] = "Nächster",
    [TXT_STREAM_BANG] = "Musiktitel",
    [TXT_PLAY_ORDER] = "WIEDERGABEFOLGE",
    [TXT_SEQUENTIAL] = "REIHENFOLGE",
    [TXT_SHUFFLE] = "ZUFALL",
    [TXT_AUDIO_SUB] = "TON & SUB",
    [TXT_NEXT_PLAY] = "Nächste",
    [TXT_BACK] = "Wiedergabe",
    [TXT_AUDIO_LABEL] = "AUDIO: %s%s%s",
    [TXT_SUBS_LABEL] = "UT:     %s%s%s",
    [TXT_OFF] = "Aus",
    [TXT_NOT_DETECTED] = "nicht erkannt",

    /* Music playback */
    [TXT_NOW_PLAYING] = "WIRD ABGESPIELT",
    [TXT_VOLUME_LINE] = "MP3  %d%% LAUTSTÄRKE  SELECT PAUSE",
    [TXT_FULLSCREEN_MUSIC] = "MUSIK // %.48s",
    [TXT_MUSIC_CONTROLS] = "SELECT PAUSE  START STOPP  O PRESETS",
    [TXT_MUSIC_SETUP_CONTROLS] = "X START   O ZURÜCK   [] HILFE",
    [TXT_VIDEO_SETUP_CONTROLS] = "X START   O ZURÜCK   [] HILFE",
    [TXT_LIBRARY_CONTROLS] = "X ÖFFNEN   O LOKAL   SELECT EINSTELLUNGEN/HILFE",
    [TXT_INFO_CONTROLS] = "O / TRIANGLE ZURÜCK     X ZUR BIBLIOTHEK",

    /* Status messages */
    [TXT_CONNECTING_WIFI] = "WLAN verbindet (O: Abbruch)",
    [TXT_WIFI_NOT_READY] = "WLAN aus - Quadrat: verbinden",
    [TXT_LOADING_LIBRARY] = "Bibliothek wird geladen ...",
    [TXT_LIBRARY_ATTEMPT] = "Bibliothek: Versuch %d/%d, %us [O]",
    [TXT_LIBRARY_CANCELLED] = "Laden abgebrochen. Quadrat: neu laden",
    [TXT_NETWORK_STOPPING] = "Netzwerkanfrage wird beendet",
    [TXT_SERVER_ERROR] = "Serverfehler: %08X",
    [TXT_NETWORK_FAILED] = "%s fehlgeschlagen: %08X",
    [TXT_RESUMING] = "Wiedergabe ab %d s ...",
    [TXT_WIFI_RETRY] = "WLAN nicht bereit - X erneut drücken",
    [TXT_STARTING_MUSIC] = "Musikstream wird gestartet",
    [TXT_STARTING_VIDEO] = "H.264-Video startet",
    [TXT_INTERRUPTED] = "WLAN unterbrochen. WLAN verbinden, X zum Fortsetzen.",
    [TXT_MUSIC_ENDED] = "Musik beendet | Audio %d",
    [TXT_VIDEO_ENDED] = "Video beendet: %d Frames",
    [TXT_NEXT_EPISODE] = "Nächste Episode: %.58s",
    [TXT_NEXT_TRACK] = "Nächster Titel: %.58s",

    [TXT_CAVE_FOG] = "Nebel",
    [TXT_CAVE_TEXTURE] = "Multitextur",
    [TXT_CAVE_HAIR] = "Haareffekt",
    [TXT_CAVE_ALPHA] = "Transparente Haare",
    [TXT_CAVE_BEAT] = "Beat-Reaktion",
    [TXT_CAVE_SENSITIVITY] = "Beat-Empfindlichkeit (0-16)",
    [TXT_CAVE_AMPLITUDE] = "Beat-Stärke (0-16)",
    [TXT_CAVE_STYLE] = "Stil (-1: automatisch)",
    [TXT_CAVE_SPEED] = "Geschwindigkeit (%)",
    [TXT_CAVE_INVERT_Y] = "Flug-Y invertieren",
    [TXT_CAVE_NOISE] = "Wandrauheit",
    [TXT_CAVE_FLIGHT_SENSITIVITY] = "Flugempfindlichkeit",
    [TXT_CAVE_FLIGHT_INERTIA] = "Flugträgheit",
    [TXT_CAVE_AUTOPILOT] = "Autopilot-Schiff",
    [TXT_PRESET_LIVE] = "Lebendige Übergänge",

    [TXT_PRESET_RANDOM] = "Zusätzliche Zufallszeit (s)",
    [TXT_PRESET_HARD] = "Harte Beat-Wechsel",
    [TXT_PRESET_THRESHOLD] = "Wechselschwelle (%)",
    [TXT_PRESET_HALFLIFE] = "Schwellen-Erholung (s)",

    [TXT_VISUAL_OPTIONS] = "Visualisierungsoptionen",
    [TXT_VISUAL_OPTIONS_HELP] = "HOCH/RUNTER: Zeile LINKS/RECHTS: Wert O: OK",

    [TXT_RADIO] = "Internetradio",
    [TXT_RADIO_PAUSED] = "Radiopause SELECT: live START: Stopp",
    [TXT_STREAM_RECONNECT] = "Neu in 5s. X: erneut; START: Stopp",
    [TXT_STREAM_WIFI] = "WLAN neu verbinden - START: Stopp",
    [TXT_STREAM_SERVER] = "Server verbinden - START: Stopp",
    [TXT_STREAM_RESUME] = "Wiedergabe fortsetzen - START: Stopp",
    [TXT_STREAM_DECODER] = "Decoder-Neustart in 5s. START: Stopp",
    [TXT_STREAM_DECODER_FAILED] = "AVC: 3 Neustarts erfolglos",
    [TXT_STREAM_START_WAIT] = "%us warten - START: Stopp",
    [TXT_STREAM_WAIT_DATA] = "Warte auf abspielbare Videodaten",
    [TXT_RADIO_RECONNECT] = "Radio in 5s verbinden - START: Stopp",
    [TXT_PLAYLIST] = "Wiedergabeliste",
    [TXT_PLAYLIST_UP] = "Nach oben",
    [TXT_PLAYLIST_DOWN] = "Nach unten",
    [TXT_PLAYLIST_REMOVE] = "Eintrag entfernen",
    [TXT_PLAYLIST_ENABLE] = "Listenreihenfolge nutzen",
    [TXT_PLAYLIST_DISABLE] = "Ordnerreihenfolge nutzen",
    [TXT_PLAYLIST_HINT] = "X: Start | Dreieck: Liste bearbeiten",
    [TXT_QUEUE_REPEAT_OFF] = "Liste wiederholen: aus",
    [TXT_QUEUE_REPEAT_ONE] = "Liste wiederholen: eine Datei",
    [TXT_QUEUE_REPEAT_ALL] = "Liste wiederholen: alle",
    [TXT_QUEUE_SHUFFLE_OFF] = "Listen-Zufall: aus",
    [TXT_QUEUE_SHUFFLE_ON] = "Listen-Zufall: an",

    [TXT_FLIGHT_HEALTH] = "SCHILD",
    [TXT_FLIGHT_SCORE] = "Punkte",
    [TXT_FLIGHT_HALL] = "Bestenliste",
    [TXT_FLIGHT_RETURN] = "X / O: weiter",
    [TXT_FLIGHT_SAVE_FAILED] = "Speichern fehlgeschlagen",
    [TXT_FLIGHT_GAME_OVER] = "GAME OVER",
    [TXT_FLIGHT_START] = "Spiel starten",
    [TXT_FLIGHT_EXIT] = "Verlassen",
    [TXT_FLIGHT_HOLD_EXIT] = "L + R: verlassen",
    [TXT_FLIGHT_EMPTY] = "Noch keine Punkte",
    [TXT_FLIGHT_MENU_HELP] = "HOCH / RUNTER   X: OK   O: Ende",

    [TXT_SETTINGS_EPISODE_SECONDS] = "Folge-Wartezeit (0=aus)",
    [TXT_PROVIDER_VIEWS] = "Anbieteransichten",
    [TXT_PROVIDER_CONTINUE] = "Weiterschauen",
    [TXT_PROVIDER_RECENT] = "Neu hinzugefügt",
    [TXT_PROVIDER_UNWATCHED] = "Ungesehen",
    [TXT_PROVIDER_COLLECTIONS] = "Sammlungen",
    [TXT_PROVIDER_PAGE] = "Nächste Seite",

    [TXT_EPISODE_COUNTDOWN] = "Nächstes Video in %d Sekunden",
    [TXT_EPISODE_COUNTDOWN_HELP] = "X: Sofort   O / START: Abbruch",
    [TXT_SERIES_SAVE] = "X Start O Zurück [] Hilfe /\\ Merken",
    [TXT_SERIES_REMOVE] = "X Start O Zurück [] Hilfe /\\ Vergessen"
};
