/* Each entry is keyed by the UI role it serves; order no longer matters. */
static const char *const lang_en[TXT_COUNT] = {
    /* Illustrated help; page text lives in help_en.h. */
    [TXT_HELP] = "HELP",
    [TXT_HELP_OPEN] = "Help - buttons and quick guides",
    [TXT_HELP_POSITION] = "Topic %d/%d   Page %d/%d",
    [TXT_HELP_KEYS] = "GOLD: USED HERE",
    [TXT_HELP_NAV] = "L / R TOPIC    UP / DOWN PAGE",
    [TXT_HELP_BACK] = "O BACK - NO SETTINGS ARE CHANGED",

    /* Offline library and transfer status. */
    [TXT_LOCAL_STORAGE] = "LOCAL STORAGE",
    [TXT_DOWNLOADS] = "SERVER QUEUE",
    [TXT_CONVERTING] = "Waiting / converting on server",
    [TXT_DOWNLOADING] = "Downloading to Memory Stick",
    [TXT_VERIFYING] = "Verifying SHA256 checksum",
    [TXT_DOWNLOAD_STOPPING] = "Stopping transfer...",
    [TXT_DOWNLOAD_ETA] = "Remaining: %u seconds",
    [TXT_DOWNLOAD_CANCEL] = "O STOP DOWNLOAD (SERVER JOB IS KEPT)",
    [TXT_DOWNLOAD_BACK] = "X / O BACK",
    [TXT_DOWNLOAD_RETRY] = "Interrupted - select again to resume",
    [TXT_DOWNLOAD_SPACE] = "Not enough free Memory Stick space",
    [TXT_DOWNLOAD_DELETE] = "Delete this local download?",
    [TXT_DOWNLOAD_CONFIRM] = "X DELETE   O KEEP",
    [TXT_DOWNLOAD_QUEUE_HELP] = "X DOWNLOAD  [] LOCAL  SELECT HELP  O BACK",
    [TXT_DOWNLOAD_LOCAL_HELP] = "X PLAY  [] QUEUE  SELECT HELP  O BACK",
    [TXT_PLAY_MODE] = "Playback",
    [TXT_STREAM_MODE] = "Streaming",
    [TXT_DOWNLOAD_MODE] = "Download, then play",
    [TXT_DOWNLOAD_PROFILE] = "LCD/TV profile mismatch",
    [TXT_DOWNLOAD_LCD_FILE] = "File: LCD (480 x 272)",
    [TXT_DOWNLOAD_TV_FILE] = "File: TV (720 x 480)",
    [TXT_DOWNLOAD_LCD_HELP] = "Unplug TV cable or download TV version",
    [TXT_DOWNLOAD_TV_HELP] = "Connect component TV or download LCD version",

    /* General settings and on-device text entry. */
    [TXT_SETTINGS] = "SETTINGS",
    [TXT_SETTINGS_HELP] = "UP/DOWN CHOOSE   LEFT/RIGHT CHANGE",
    [TXT_SETTINGS_SAVED] = "Settings saved",
    [TXT_SETTINGS_FAILED] = "Save failed; changes cancelled",
    [TXT_SETTINGS_HINT] = "SELECT: SETTINGS",
    [TXT_SETTINGS_SAVE_HELP] = "START SAVE   O CANCEL   X TEXT / NUMBER",
    [TXT_SETTINGS_ON] = "On",
    [TXT_INVALID_SETTING] = "Invalid value",
    [TXT_KEYBOARD_HELP] = "X ADD  L DELETE  R CLEAR  START OK  O CANCEL",

    [TXT_SETTINGS_HOST] = "Server host",
    [TXT_SETTINGS_PORT] = "Server port",
    [TXT_SETTINGS_PASSWORD] = "Password",
    [TXT_SETTINGS_HTTPS] = "HTTPS",
    [TXT_SETTINGS_LANGUAGE] = "Language",
    [TXT_SETTINGS_TV] = "TV UI at start",
    [TXT_SETTINGS_AUDIO] = "Audio track",
    [TXT_SETTINGS_SUBTITLE] = "Subtitle track",
    [TXT_SETTINGS_QUALITY] = "Audio quality",
    [TXT_SETTINGS_FPS] = "Video fps",
    [TXT_SETTINGS_VOLUME] = "Volume",
    [TXT_SETTINGS_SHUFFLE] = "Shuffle",
    [TXT_SETTINGS_PRESET] = "Preset file",
    [TXT_SETTINGS_AUTO] = "Preset mode",
    [TXT_SETTINGS_SECONDS] = "Preset seconds",
    [TXT_SETTINGS_FADE] = "Fade ms",
    [TXT_SETTINGS_DEBUG] = "Debug diagnostics",
    [TXT_MUSIC_FINISHED] = "Music ended",
    [TXT_VIDEO_FINISHED] = "Video ended",

    [TXT_TLS_FIRST] = "HTTPS certificate saved",
    [TXT_TLS_CHANGED] = "HTTPS certificate changed!",
    [TXT_TLS_SAVE_FAILED] = "Cannot save HTTPS certificate",
    [TXT_FRAME_RATE] = "Frame rate",
    [TXT_PRESETS] = "MILKDROP PRESETS",
    [TXT_PRESET_CONTROLS] = "UP/DN SELECT  L/R PAGE  X APPLY  O BACK",
    [TXT_PRESET_LIMIT] = "128 files max",
    [TXT_PRESET_AUTO_STATUS] = "Auto: %s | %ds",
    [TXT_PRESET_AUTO_HELP] = "SQUARE: MODE   TRIANGLE: INTERVAL",
    [TXT_PRESET_AUTO_OFF] = "Off",
    [TXT_PRESET_AUTO_ORDER] = "Order",
    [TXT_PRESET_AUTO_RANDOM] = "Random",
    [TXT_PRESET_AUTO_RATED] = "Rated",
    /* Fullscreen transport overlay */
    [TXT_TRANSPORT_PAUSE] = "Pause",
    [TXT_TRANSPORT_RESUME] = "Play",

    /* Custom visualization: two compact lines, with field/line below. */
    [TXT_PRESET_MISSING] = "Preset file missing",
    [TXT_PRESET_INVALID] = "Invalid preset value",
    [TXT_PRESET_UNSUPPORTED] = "Unsupported preset field",
    [TXT_PRESET_IO] = "Cannot read preset",

    /* Native TV sidebar */
    [TXT_TV_SAVED_LINE1] = "Saved for",
    [TXT_TV_SAVED_LINE2] = "next",
    [TXT_TV_SAVED_LINE3] = "playback.",

    [TXT_TV_VOLUME] = "VOLUME: %d%%",

    /* Library and loading panels */
    [TXT_MEDIA_LIBRARY] = "MEDIA LIBRARY",
    [TXT_PREPARING_MEDIA] = "PREPARING MEDIA",
    [TXT_READING_MEDIA] = "READING MEDIA INFORMATION",
    [TXT_LOADING_TRACKS] = "Loading audio tracks and subtitles...",
    [TXT_PREPARING_SUBTITLES] = "Preparing subtitles...",
    [TXT_PREPARATION_WAIT] = "%u s   O CANCEL",
    [TXT_SOURCE_WAKING] = "The source may be waking over SMB.",
    [TXT_PLEASE_WAIT] = "PLEASE WAIT",
    [TXT_NO_VIDEO] = "No video",
    [TXT_STREAM_HAS] = "stream has",
    [TXT_STARTED] = "started",

    [TXT_LIBRARY] = "LIBRARY",
    [TXT_NO_ENTRIES] = "No entries -- [] reload",
    [TXT_SELECTED] = "SELECTED",
    [TXT_WAITING] = "Waiting...",
    [TXT_FOLDER] = "FOLDER",
    [TXT_MUSIC] = "MUSIC",
    [TXT_VIDEO] = "VIDEO",
    [TXT_ENTRIES] = "%d entries",
    [TXT_PROFILE] = "Profile %d",
    [TXT_AVC_READY] = "AVC READY",
    [TXT_AVC_ERROR] = "AVC ERROR",

    /* File information */
    [TXT_FILE_DETAILS] = "FILE DETAILS",
    [TXT_MUSIC_STREAM] = "MUSIC STREAM",
    [TXT_VIDEO_STREAM] = "H.264 VIDEO",
    [TXT_DURATION] = "DURATION: %d:%02d",
    [TXT_DURATION_UNKNOWN] = "DURATION: SERVER UNKNOWN",
    [TXT_AUDIO_TRACKS] = "AUDIO TRACKS: %d",
    [TXT_SUBTITLE_TRACKS] = "SUBTITLE TRACKS: %d",
    [TXT_STREAMS] = "STREAMS",
    [TXT_NO_TRACKS] = "No tracks.",
    [TXT_STREAM_OPTIONS] = "STREAM OPTIONS",
    [TXT_QUALITY] = "QUALITY",
    [TXT_SAVED_FOR] = "Saved for",
    [TXT_NEXT_MUSIC] = "next music",
    [TXT_STREAM_BANG] = "stream!",
    [TXT_PLAY_ORDER] = "PLAY ORDER",
    [TXT_SEQUENTIAL] = "SEQUENTIAL",
    [TXT_SHUFFLE] = "SHUFFLE",
    [TXT_AUDIO_SUB] = "AUDIO & SUB",
    [TXT_NEXT_PLAY] = "next play-",
    [TXT_BACK] = "back",
    [TXT_AUDIO_LABEL] = "AUDIO: %s%s%s",
    [TXT_SUBS_LABEL] = "SUBS:  %s%s%s",
    [TXT_OFF] = "Off",
    [TXT_NOT_DETECTED] = "not detected",
    [TXT_NOW_PLAYING] = "NOW PLAYING",
    [TXT_VOLUME_LINE] = "MP3  %d%% VOLUME  SELECT PAUSE",
    [TXT_FULLSCREEN_MUSIC] = "MUSIC // %.48s",
    [TXT_MUSIC_CONTROLS] = "SELECT PAUSE  START STOP  O PRESETS",
    [TXT_MUSIC_SETUP_CONTROLS] = "X START   O BACK   [] HELP",
    [TXT_VIDEO_SETUP_CONTROLS] = "X START   O BACK   [] HELP",
    [TXT_LIBRARY_CONTROLS] = "X OPEN   O LOCAL   SELECT SETTINGS/HELP",
    [TXT_INFO_CONTROLS] = "O / TRIANGLE BACK     X RETURNS TO LIBRARY",
    [TXT_CONNECTING_WIFI] = "Wi-Fi: connecting (O: cancel)",
    [TXT_WIFI_NOT_READY] = "Wi-Fi offline - SQUARE: retry",
    [TXT_LOADING_LIBRARY] = "Loading library ...",
    [TXT_LIBRARY_CANCELLED] = "Loading cancelled. Square: retry",
    [TXT_NETWORK_STOPPING] = "Stopping network request",
    [TXT_SERVER_ERROR] = "Server error: %08X",
    [TXT_NETWORK_FAILED] = "%s failed: %08X",
    [TXT_RESUMING] = "Resuming at %d s ...",
    [TXT_WIFI_RETRY] = "Wi-Fi not ready - press X again",
    [TXT_STARTING_MUSIC] = "Starting music stream",
    [TXT_STARTING_VIDEO] = "Starting H.264 video",
    [TXT_INTERRUPTED] = "Wi-Fi interrupted. Reconnect Wi-Fi, press X to resume.",
    [TXT_MUSIC_ENDED] = "Music ended | Audio %d",
    [TXT_VIDEO_ENDED] = "Video ended: %d frames",
    [TXT_NEXT_EPISODE] = "Next episode: %.58s",
    [TXT_NEXT_TRACK] = "Next track: %.58s",

    [TXT_RADIO] = "Internet radio",
    [TXT_RADIO_PAUSED] = "Radio paused - SELECT: live START: stop",
    [TXT_RADIO_RECONNECT] = "Radio retry in 5s - START: stop"};
