#ifndef PSP_STREAMER_LANGUAGE_H
#define PSP_STREAMER_LANGUAGE_H

typedef enum {
    TXT_MEDIA_LIBRARY, TXT_PREPARING_MEDIA, TXT_READING_MEDIA,
    TXT_LOADING_TRACKS, TXT_SOURCE_WAKING, TXT_PLEASE_WAIT,
    TXT_NO_VIDEO, TXT_STREAM_HAS, TXT_STARTED,
    TXT_LIBRARY, TXT_NO_ENTRIES, TXT_SELECTED, TXT_WAITING,
    TXT_FOLDER, TXT_MUSIC, TXT_VIDEO, TXT_ENTRIES, TXT_PROFILE,
    TXT_AVC_READY, TXT_AVC_ERROR, TXT_FILE_DETAILS, TXT_MUSIC_STREAM,
    TXT_VIDEO_STREAM, TXT_DURATION, TXT_DURATION_UNKNOWN, TXT_AUDIO_TRACKS,
    TXT_SUBTITLE_TRACKS, TXT_STREAMS, TXT_NO_TRACKS, TXT_STREAM_OPTIONS,
    TXT_QUALITY, TXT_SAVED_FOR, TXT_NEXT_MUSIC, TXT_STREAM_BANG,
    TXT_AUDIO_SUB, TXT_NEXT_PLAY, TXT_BACK, TXT_AUDIO_LABEL,
    TXT_SUBS_LABEL, TXT_OFF, TXT_NOT_DETECTED, TXT_NOW_PLAYING,
    TXT_VOLUME_LINE, TXT_FULLSCREEN_MUSIC, TXT_MUSIC_CONTROLS,
    TXT_MUSIC_SETUP_CONTROLS, TXT_VIDEO_SETUP_CONTROLS, TXT_LIBRARY_CONTROLS,
    TXT_INFO_CONTROLS, TXT_CONNECTING_WIFI, TXT_WIFI_NOT_READY,
    TXT_LOADING_LIBRARY, TXT_SERVER_ERROR, TXT_NETWORK_FAILED,
    TXT_RESUMING, TXT_WIFI_RETRY, TXT_STARTING_MUSIC, TXT_STARTING_VIDEO,
    TXT_INTERRUPTED, TXT_MUSIC_ENDED, TXT_VIDEO_ENDED, TXT_NEXT_EPISODE, TXT_NEXT_TRACK,
    TXT_COUNT
} TextId;

const char *tr(TextId id);
void language_set_code(const char *code);
const char *language_code(void);

#endif
