/* Named UTF-8 UI strings. XSTR(id, English, German).
 * Keep Xbox controller names, format placeholders and their order intact. */
XSTR(ON, "On", "An")
XSTR(OFF, "Off", "Aus")
XSTR(PLAY, "Play", "Abspielen")
XSTR(PAUSE, "Pause", "Pause")
XSTR(RESUME, "Resume", "Fortsetzen")
XSTR(PLAYING, "Playing", "Wiedergabe")
XSTR(PAUSED, "Paused", "Pausiert")
XSTR(STOPPED, "Stopped", "Gestoppt")
XSTR(STOP, "Stop", "Stopp")
XSTR(FINISHED, "Playback finished", "Wiedergabe beendet")

XSTR(HELP, "HELP", "HILFE")
XSTR(SETTINGS, "SETTINGS", "OPTIONEN")
XSTR(INFO, "INFO", "INFO")
XSTR(PLAYING_TITLE, "PLAYING", "LÄUFT")
XSTR(PAUSED_TITLE, "PAUSED", "PAUSIERT")
XSTR(OPTIONS, "OPTIONS", "AUSWAHL")
XSTR(LIBRARY, "LIBRARY", "BIBLIOTHEK")
XSTR(SELECT, "A: Select", "A: Auswahl")
XSTR(BACK, "B: Back", "B: Zurück")
XSTR(OPEN_SETTINGS, "X: Settings", "X: Optionen")
XSTR(OPEN_HELP, "Y: Help", "Y: Hilfe")
XSTR(EXIT, "Back: Exit", "Back: Ende")
XSTR(CANCEL, "B: Cancel", "B: Abbruch")
XSTR(LOADING, "Loading...", "Laden...")
XSTR(EMPTY, "No entries", "Keine Einträge")
XSTR(FAVORITES, "Favorites", "Favoriten")
XSTR(RECENT, "Recently played", "Zuletzt gespielt")
XSTR(PLAYLIST, "Playlist", "Wiedergabeliste")
XSTR(SEARCH, "Search", "Suche")

XSTR(HELP_PLAY, "A: Open / Play / Pause; B: Back / Stop", "A: Öffnen / Start / Pause; B: Zurück / Stopp")
XSTR(HELP_CONTROLS, "Start: Playback menu (chapters, files, seek)", "Start: Wiedergabemenü (Kapitel, Dateien, Zeit)")
XSTR(HELP_VOLUME, "Up/Down: Volume; Y: Fullscreen", "Hoch/Runter: Lautstärke; Y: Vollbild")
XSTR(HELP_SKIP, "LB / RB: Previous / next file; triggers: chapters", "LB/RB: Vorige/nächste Datei; Trigger: Kapitel")
XSTR(HELP_SPECTRUM, "Music X: Visualizations; Video X: Playback", "Musik X: Visualisierungen; Video X: Wiedergabe")
XSTR(HELP_MENU, "Menu X: Settings; Y: Help; options Y: Info", "Menü X: Optionen; Y: Hilfe; Auswahl Y: Infos")
XSTR(HELP_RESUME, "Options X: Start / Resume; Back: Dashboard", "Auswahl X: Anfang/Fortsetzen; Back: Dashboard")
XSTR(HELP_ACTIONS, "Library LB: Favorites / queue; RB: Search", "Bibliothek LB: Favoriten/Liste; RB: Suche")

XSTR(LOADING_CANCEL, "Loading... B cancels", "Laden... B bricht ab")
XSTR(CONNECTING, "Connecting...", "Verbinden...")
XSTR(BUFFERING, "Buffering... B: Stop", "Puffern... B: Stopp")
XSTR(PLAYER_FAILED, "Cannot start player", "Player konnte nicht starten")
XSTR(WORKER_FAILED, "Cannot start network worker", "Netzwerk-Task konnte nicht starten")
XSTR(PATH_LONG, "Folder path too long", "Ordnerpfad zu lang")
XSTR(FOLDER_END, "End of folder (no next/previous file)", "Ende der Liste (keine weitere Datei)")
XSTR(INVALID_REPLY, "Invalid reply. Update server to 0.1.71.", "Ungültige Antwort. Server aktualisieren.")
XSTR(OPTIONS_HINT, "A: Play | X: Resume/start | Y: Info", "A: Start | X: Fortsetzen/Anfang | Y: Infos")
XSTR(LIST_HINT, "%d entries | Left/Right: page | A: Open", "%d Einträge | Links/Rechts: Seite | A: Öffnen")
XSTR(RETRY_FAILED, "Retry failed; select Play to resume", "Verbindung fehlgeschlagen; erneut Start wählen")
XSTR(STREAM_FAILED, "Stream failed", "Stream fehlgeschlagen")
XSTR(RETRY, "Connection lost: retry %d/3 | B: Cancel", "Verbindung weg: Versuch %d/3 | B: Abbruch")
XSTR(NEXT_COUNTDOWN, "Next episode in %d seconds | A: Now | B: Cancel", "Nächste Folge in %d Sekunden | A: Jetzt | B: Abbruch")

XSTR(KEEP_OUTPUT, "Keep this output?", "Ausgabe beibehalten?")
XSTR(KEEP_OUTPUT_HELP, "A: Keep | B: Restore previous mode", "A: Behalten | B: Vorigen Modus herstellen")
XSTR(RESTORE_COUNTDOWN, "Automatic restore in %u seconds", "Automatisch zurück in %u Sekunden")
XSTR(OUTPUT_HELP, "A: Try mode | B: Back (no EEPROM changes)", "A: Testen | B: Zurück (EEPROM unverändert)")
XSTR(SERVER_IP, "Server host: %s", "Serveradresse: %s")
XSTR(PORT, "Port: %s", "Port: %s")
XSTR(PASSWORD, "Password: %s", "Passwort: %s")
XSTR(EMPTY_PASSWORD, "(empty)", "(leer)")
XSTR(TEST_SERVER, "Test connection (HTTP)", "Verbindung testen (HTTP)")
XSTR(SAVE_SERVER, "Save and connect", "Speichern und verbinden")
XSTR(EDIT_HELP, "A: Edit / Execute | B: Cancel", "A: Ändern / Ausführen | B: Abbruch")
XSTR(KEYBOARD_HELP, "A: Type | X: Del | Y: Clear | Start: Save | B: Back", "A: Zeichen | X: Löschen | Y: Leeren | Start: OK | B: Zurück")
XSTR(INVALID_SERVER, "Enter a hostname/IP and port 1-65535", "Hostname/IP und Port 1-65535 eingeben")
XSTR(SAVE_FAILED, "Cannot save server.cfg; previous settings retained", "Speichern fehlgeschlagen; alte Einstellungen bleiben")
XSTR(SERVER_OK, "Server connection successful (not saved yet)", "Server erreichbar (noch nicht gespeichert)")
XSTR(SERVER_SETUP, "X: Settings > Server connection (network=%d)", "X: Optionen > Serververbindung (Netzwerk=%d)")

XSTR(ANALYSIS, "Analysis: %s", "Analyse: %s")
XSTR(FFT, "Desktop FFT", "Desktop FFT")
XSTR(LEGACY, "Legacy (12 bands)", "Klassisch (12 Bänder)")
XSTR(BANDS, "FFT bands: %d", "FFT-Bänder: %d")
XSTR(GAIN, "Display gain: %d dB (FFT)", "Anzeigeverstärkung: %d dB (FFT)")
XSTR(COLORS, "Colors: %s", "Farben: %s")
XSTR(RAINBOW, "Rainbow", "Regenbogen")
XSTR(ICE, "Ice", "Eis")
XSTR(FIRE, "Fire", "Feuer")
XSTR(LEDS, "LED segments: %s", "LED-Segmente: %s")
XSTR(LED_COUNT, "LED count: %d", "LED-Anzahl: %d")
XSTR(PEAK, "Peak hold: %s", "Spitzenwert halten: %s")

XSTR(AUTOPLAY, "Autoplay next: %s", "Automatisch weiterspielen: %s")
XSTR(REPEAT_CURRENT, "Repeat current: %s", "Aktuelle Datei wiederholen: %s")
XSTR(FOLDER_SHUFFLE, "Folder shuffle (music): %s", "Ordner-Zufallswiedergabe (Musik): %s")
XSTR(SPECTRUM, "Music spectrum: %s", "Musikspektrum: %s")
XSTR(VIDEO_QUALITY, "Video quality: %s", "Videoqualität: %s")
XSTR(VOLUME, "Volume: %d%%", "Lautstärke: %d%%")
XSTR(AUDIO, "Audio: %s", "Tonspur: %s")
XSTR(SOURCE_DEFAULT, "Source default", "Quellenvorgabe")
XSTR(SUBTITLES, "Subtitles: %s", "Untertitel: %s")
XSTR(SERVER_CONNECTION, "Server connection >", "Serververbindung >")
XSTR(SPECTRUM_SETTINGS, "Spectrum settings >", "Spektrum-Einstellungen >")
XSTR(VISUAL_SETTINGS, "Visualization settings >", "Visualisierungs-Einstellungen >")
XSTR(DEBUG, "Debug logging: %s", "Diagnoseprotokoll: %s")
XSTR(NEXT_DELAY, "Next episode countdown: %d seconds", "Nächste Folge: Countdown %d Sekunden")
XSTR(VIDEO_CODEC, "Video codec: %s", "Video-Codec: %s")
XSTR(TV_SHAPE, "TV shape: %s", "Bildformat: %s")
XSTR(OUTPUT, "Display output: %dx%d >", "Bildausgabe: %dx%d >")
XSTR(DOWNMIX, "Audio downmix: %s", "Audio-Downmix: %s")
XSTR(RENDERER, "Video renderer: %s", "Video-Renderer: %s")
XSTR(LANGUAGE, "UI language: %s", "Menüsprache: %s")
XSTR(AUDIO_QUALITY, "MP2 quality (48 kHz): %s", "MP2-Qualität (48 kHz): %s")

XSTR(TRACK_INFO, "%d:%02d | %d audio / %d subtitle tracks", "%d:%02d | %d Tonspuren / %d Untertitel")
XSTR(NO_SYNOPSIS, "No synopsis supplied by this source.", "Diese Quelle liefert keine Beschreibung.")
XSTR(PLAYBACK_HELP, "Start / X: Controls   A: Pause   B: Stop", "Start / X: Steuerung   A: Pause   B: Stopp")
XSTR(SEEK_HELP, "Left / Right: -/+30s   Up / Down: Volume", "Links/Rechts: -/+30s   Hoch/Runter: Lautstärke")
XSTR(RESUME_AT, "Resume at %d:%02d (X: from start)", "Fortsetzen bei %d:%02d (X: von Anfang)")
XSTR(NO_AUDIO, "No audio", "Kein Ton")
XSTR(VIDEO, "Video: %s / MPEG-%d", "Video: %s / MPEG-%d")
XSTR(BACK_30, "Back 30 seconds", "30 Sekunden zurück")
XSTR(FORWARD_30, "Forward 30 seconds", "30 Sekunden vor")
XSTR(PREV_CHAPTER, "Previous chapter", "Voriges Kapitel")
XSTR(NEXT_CHAPTER, "Next chapter", "Nächstes Kapitel")
XSTR(NO_PREV_CHAPTER, "Previous chapter (none available)", "Voriges Kapitel (nicht vorhanden)")
XSTR(NO_NEXT_CHAPTER, "Next chapter (none available)", "Nächstes Kapitel (nicht vorhanden)")
XSTR(PREV_FILE, "Previous file", "Vorige Datei")
XSTR(NEXT_FILE, "Next file", "Nächste Datei")
XSTR(CONTROLS_HELP, "D-pad: select | A: execute | B: close", "Steuerkreuz: Auswahl | A: Ausführen | B: Zurück")
XSTR(UNKNOWN_LANGUAGE, "Language unspecified", "Sprache unbekannt")
XSTR(ENGLISH, "English", "Englisch")
XSTR(GERMAN, "German", "Deutsch")
XSTR(JAPANESE, "Japanese", "Japanisch")
XSTR(FRENCH, "French", "Französisch")
XSTR(SPANISH, "Spanish", "Spanisch")
XSTR(ITALIAN, "Italian", "Italienisch")

XSTR(FAVORITE_ADD, "Add favorite", "Favorit hinzufügen")
XSTR(FAVORITE_REMOVE, "Remove favorite", "Favorit entfernen")
XSTR(QUEUE_ADD, "Add to playlist", "Zur Wiedergabeliste hinzufügen")
XSTR(QUEUE_REMOVE, "Remove from playlist", "Aus Wiedergabeliste entfernen")
XSTR(QUEUE_UP, "Move up", "Nach oben verschieben")
XSTR(QUEUE_DOWN, "Move down", "Nach unten verschieben")
XSTR(QUEUE_ENABLED, "Use playlist: %s", "Wiedergabeliste nutzen: %s")
XSTR(QUEUE_REPEAT, "Playlist repeat: %s", "Liste wiederholen: %s")
XSTR(REPEAT_ONE, "One", "Eine Datei")
XSTR(REPEAT_ALL, "All", "Alle")
XSTR(QUEUE_SHUFFLE, "Playlist shuffle: %s", "Listen-Zufallswiedergabe: %s")
XSTR(ACTIONS_HELP, "A: Execute | B: Back | shared with web/PSP", "A: Ausführen | B: Zurück | mit Web/PSP geteilt")
XSTR(SEARCH_STATE, "Search: %d results | running=%d limited=%d errors=%d", "Suche: %d Treffer | läuft=%d Limit=%d Fehler=%d")
XSTR(SEARCH_SHORT, "Search needs at least 2 characters", "Suche benötigt mindestens 2 Zeichen")
XSTR(ACTIONS_HINT, "LB: Item actions | RB: Search | Start: Refresh", "LB: Dateiaktionen | RB: Suche | Start: Aktualisieren")
XSTR(DISPLAY_RESTORED, "Display allocation failed; mode restored", "Bildspeicher fehlt; voriger Modus hergestellt")
XSTR(AUTOPLAY_CANCELLED, "Autoplay cancelled", "Automatisches Weiterspielen abgebrochen")
XSTR(RETRY_CANCELLED, "Retry cancelled; select Play to resume", "Neuverbinden abgebrochen; Start setzt fort")
XSTR(CANCELLED, "Cancelled", "Abgebrochen")
XSTR(STOP_TIMER,"Stop timer: %d min (0 = off)","Stopptimer: %d Min. (0 = aus)")
XSTR(TIMER_STOPPED,"Stopped by sleep timer","Durch Stopptimer beendet")
XSTR(SERIES_SAVE,"Save tracks for this series/folder","Spuren für Serie/Ordner speichern")
XSTR(SERIES_REMOVE,"Remove series/folder preference","Serien-/Ordnervorgabe entfernen")
XSTR(SERIES_UPDATED,"Series/folder preference updated","Serien-/Ordnervorgabe gespeichert")
XSTR(HELP_LIBRARY_TITLE,"Library","Bibliothek")
XSTR(HELP_VIDEO_TITLE,"Video","Video")
XSTR(HELP_MUSIC_TITLE,"Music / visualizations","Musik / Visualisierung")
XSTR(HELP_EDIT_TITLE,"Settings / keyboard","Einstellungen / Tastatur")
XSTR(HELP_SEARCH_HINT,"R: search all sources","R: alle Quellen durchsuchen")
XSTR(HELP_EXIT_HINT,"BACK: exit application","BACK: Anwendung beenden")
XSTR(HELP_SEEK_HINT,"Left / right: seek 30 s","Links / rechts: 30 s springen")
XSTR(HELP_CHAPTER_HINT,"Triggers: previous/next chapter","Trigger: voriges/nächstes Kapitel")
XSTR(HELP_FULL_HINT,"Y: fullscreen / window","Y: Vollbild / Fenster")
XSTR(HELP_STOP_HINT,"B: stop playback","B: Wiedergabe stoppen")
XSTR(HELP_MUSIC_X,"X: effect / preset settings","X: Effekt- / Preset-Einstellungen")
XSTR(HELP_FLIGHT_HINT,"Monkey: both triggers = flight","Monkey: beide Trigger = Flug")
XSTR(HELP_EDIT_MOVE,"D-pad: select / change","Steuerkreuz: wählen / ändern")
XSTR(HELP_EDIT_ACCEPT,"A: accept / insert character","A: wählen / Zeichen einfügen")
XSTR(HELP_EDIT_ERASE,"Keyboard: X erase, Y clear","Tastatur: X löschen, Y leeren")
XSTR(HELP_EDIT_DONE,"Keyboard START: accept field","Tastatur START: Feld übernehmen")
XSTR(HELP_EDIT_CANCEL,"B: return / cancel draft","B: zurück / Entwurf verwerfen")
XSTR(HELP_PAGES,"Left/right: topic  |  B: back  |  Right stick: contextual help","Links/rechts: Thema | B: zurück | Rechter Stick: Kontexthilfe")
