TARGET = FuSaFullscreenTest
OBJS = fullscreen.o
PSP_FW_VERSION = 661
BUILD_PRX = 1
USE_KERNEL_LIBS = 1
CFLAGS = -O2 -G0 -Wall -Wextra
LDFLAGS = -nostartfiles
LIBS = -lpspge_driver -lpsppower_driver -lpspsystemctrl_kernel -lgcc
PSPSDK := $(shell psp-config --pspsdk-path)
include $(PSPSDK)/lib/build.mak
fullscreen.o: scale.h snapshot.h ../psp-overclock/power_callback_slot.h
