TARGET = FuSaFullscreenTest
OBJS = fullscreen.o snapshot_vfpu.o
PSP_FW_VERSION = 661
BUILD_PRX = 1
PRX_EXPORTS = fullscreen_exports.exp
USE_KERNEL_LIBS = 1
CFLAGS = -O2 -G0 -Wall -Wextra
LDFLAGS = -nostartfiles
LIBS = -lpspge_driver -lpsppower_driver -lpspsystemctrl_kernel -lpspsysmem_kernel_660 -lgcc
PSPSDK := $(shell psp-config --pspsdk-path)
include $(PSPSDK)/lib/build.mak
fullscreen.o: scale.h snapshot.h auto_zoom.h ../psp-overclock/power_callback_slot.h
fullscreen.o: display_policy.h
