"""Bake the supplied static GLB into a tiny PSP mesh (no runtime glTF loader).

Only the model's simple colored, opaque triangle materials are supported.
Unsupported features fail explicitly rather than producing partial geometry.
Usage: python3 tools/convert_cave_ship.py model.glb psp-client/cave_ship_data.h
"""
import json
import math
from pathlib import Path
import struct
import sys


def convert(path):
    raw = Path(path).read_bytes()
    magic, version, size = struct.unpack_from('<III', raw)
    if (magic, version, size) != (0x46546c67, 2, len(raw)):
        raise ValueError('Invalid GLB 2 container')
    chunks = {}
    at = 12
    while at < size:
        length, kind = struct.unpack_from('<II', raw, at)
        chunks[kind] = raw[at + 8:at + 8 + length]
        at += 8 + length
    doc = json.loads(chunks[0x4e4f534a])
    binary = chunks[0x004e4942]
    if any(doc.get(k) for k in ('animations', 'skins', 'textures', 'extensionsUsed')):
        raise ValueError('Expected an untextured static mesh')

    def accessor(index):
        a = doc['accessors'][index]
        v = doc['bufferViews'][a['bufferView']]
        if a.get('sparse') or v.get('buffer', 0) or a.get('normalized'):
            raise ValueError('Unsupported accessor')
        fmt = {5126: 'f', 5125: 'I', 5123: 'H', 5121: 'B'}[a['componentType']]
        count = {'SCALAR': 1, 'VEC3': 3}[a['type']]
        unpack = struct.Struct('<' + fmt * count)
        offset = v.get('byteOffset', 0) + a.get('byteOffset', 0)
        return [unpack.unpack_from(binary, offset + i*v.get('byteStride', unpack.size)) for i in range(a['count'])]

    identity = [float(i % 5 == 0) for i in range(16)]
    vertices = []

    def visit(index, parent, ancestors):
        if index in ancestors:
            raise ValueError('Cyclic scene')
        node = doc['nodes'][index]
        if any(k in node for k in ('rotation', 'scale', 'translation', 'skin')):
            raise ValueError('This converter requires matrix node transforms')
        local = node.get('matrix', identity)
        world = [sum(parent[k*4+r]*local[c*4+k] for k in range(4)) for c in range(4) for r in range(4)]
        if 'mesh' in node:
            for p in doc['meshes'][node['mesh']]['primitives']:
                if p.get('mode', 4) != 4 or p.get('targets'):
                    raise ValueError('Expected static triangles')
                material = doc['materials'][p['material']]
                if material.get('alphaMode', 'OPAQUE') != 'OPAQUE':
                    raise ValueError('Expected opaque materials')
                rgb = material['pbrMetallicRoughness']['baseColorFactor'][:3]
                emission = material.get('emissiveFactor', [0, 0, 0])
                positions = accessor(p['attributes']['POSITION'])
                normals = accessor(p['attributes']['NORMAL'])
                indices = accessor(p['indices'])
                if len(indices) % 3:
                    raise ValueError('Incomplete triangle')
                for (i,) in indices:
                    v = [sum(world[k*4+r]*positions[i][k] for k in range(3))+world[12+r] for r in range(3)]
                    n = [sum(world[k*4+r]*normals[i][k] for k in range(3)) for r in range(3)]
                    # Turn the supplied model's nose toward GE -Z.
                    v[0], v[2], n[0], n[2] = -v[0], -v[2], -n[0], -n[2]
                    length = math.sqrt(sum(x*x for x in n)) or 1
                    light = .45 + .55*max(0, sum(a*b for a,b in zip(n,(-.3,.8,-.52)))/length)
                    color = 0xff000000
                    for k in range(3):
                        linear = min(1, max(0, rgb[k]*light+emission[k]))
                        channel = round(255*(12.92*linear if linear <= .0031308 else 1.055*linear**(1/2.4)-.055))
                        color |= channel << (8*k)
                    vertices.append((v, color))
        for child in node.get('children', []):
            visit(child, world, ancestors | {index})

    for root in doc['scenes'][doc.get('scene', 0)]['nodes']:
        visit(root, identity, set())
    if not vertices or len(vertices) > 4096:
        raise ValueError('Ship exceeds the bounded GU mesh budget')
    low = [min(v[k] for v,c in vertices) for k in range(3)]
    high = [max(v[k] for v,c in vertices) for k in range(3)]
    scale = .9 / max(high[k]-low[k] for k in range(3))
    rows = ['/* Generated by tools/convert_cave_ship.py. See assets/cave_ship.CREDITS.md. */',
            'static const MdVertex cave_ship_mesh[] = {']
    for v, color in vertices:
        xyz = [(v[k]-(low[k]+high[k])*.5)*scale for k in range(3)]
        rows.append('    {0,0,0x%08x,%s},' % (color, ','.join('%.7ff' % x for x in xyz)))
    rows += ['};', 'enum { CAVE_SHIP_VERTICES = sizeof(cave_ship_mesh)/sizeof(cave_ship_mesh[0]) };', '']
    return '\n'.join(rows)


if __name__ == '__main__':
    Path(sys.argv[2]).write_text(convert(sys.argv[1]), encoding='utf-8')
