"""Bake the supplied Astro Shield GLB rest pose and a small emissive texture.

No runtime skinning or image loading. Asset remains CC BY 4.0; see credits.
"""
import io
import json
from pathlib import Path
import struct
import sys
import numpy as np
from PIL import Image


def convert(source, target):
    raw = source.read_bytes()
    if struct.unpack_from('<III', raw) != (0x46546c67, 2, len(raw)):
        raise ValueError('Invalid GLB')
    chunks = {}; offset = 12
    while offset < len(raw):
        size, kind = struct.unpack_from('<II', raw, offset)
        chunks[kind] = raw[offset+8:offset+8+size]; offset += size+8
    doc = json.loads(chunks[0x4e4f534a]); binary = chunks[0x004e4942]
    def access(index):
        a = doc['accessors'][index]; view = doc['bufferViews'][a['bufferView']]
        if a.get('sparse') or a.get('normalized') or view.get('buffer', 0):
            raise ValueError('Unsupported accessor')
        dtype = np.dtype({5126:'<f4',5125:'<u4',5123:'<u2',5121:'u1'}[a['componentType']])
        width = {'SCALAR':1,'VEC2':2,'VEC3':3,'VEC4':4,'MAT4':16}[a['type']]
        return np.ndarray((a['count'], width), dtype, binary,
                          view.get('byteOffset',0)+a.get('byteOffset',0),
                          (view.get('byteStride',dtype.itemsize*width),dtype.itemsize)).copy()
    worlds = {}
    def visit(index, parent):
        if index in worlds: raise ValueError('Repeated scene node')
        node = doc['nodes'][index]
        if 'matrix' in node: matrix = np.array(node['matrix']).reshape(4,4,order='F')
        else:
            x,y,z,w = node.get('rotation',[0,0,0,1])
            matrix = np.eye(4)
            matrix[:3,:3] = [[1-2*(y*y+z*z),2*(x*y-z*w),2*(x*z+y*w)],
                             [2*(x*y+z*w),1-2*(x*x+z*z),2*(y*z-x*w)],
                             [2*(x*z-y*w),2*(y*z+x*w),1-2*(x*x+y*y)]]
            matrix[:3,:3] *= np.array(node.get('scale',[1,1,1]))
            matrix[:3,3] = node.get('translation',[0,0,0])
        worlds[index] = parent @ matrix
        for child in node.get('children',[]): visit(child, worlds[index])
    for root in doc['scenes'][doc.get('scene',0)]['nodes']: visit(root,np.eye(4))
    meshes = [(i,n) for i,n in enumerate(doc['nodes']) if 'mesh' in n]
    if len(meshes)!=1: raise ValueError('Expected one shield mesh')
    index,node = meshes[0]; primitives = doc['meshes'][node['mesh']]['primitives']
    if len(primitives)!=1: raise ValueError('Expected one shield material')
    prim = primitives[0]
    if prim.get('mode',4)!=4 or prim.get('targets'): raise ValueError('Expected triangles')
    attr=prim['attributes']; p=access(attr['POSITION']); p=np.c_[p,np.ones(len(p))]
    if 'skin' in node:
        skin=doc['skins'][node['skin']]; inverse=access(skin['inverseBindMatrices'])
        joints=access(attr['JOINTS_0']); weights=access(attr['WEIGHTS_0'])
        if not np.allclose(weights.sum(axis=1),1,atol=1e-5): raise ValueError('Invalid weights')
        posed=np.zeros_like(p)
        for v in range(len(p)):
            for j in range(4):
                bone=int(joints[v,j]); matrix=worlds[skin['joints'][bone]] @ inverse[bone].reshape(4,4,order='F')
                posed[v] += weights[v,j]*(matrix @ p[v])
        p=posed[:,:3]
    else: p=(p @ worlds[index].T)[:,:3]
    if not np.isfinite(p).all(): raise ValueError('Invalid pose')
    # Supplied shield faces along X. Stand it upright across the tunnel XY plane.
    p=p[:,[2,1,0]]; low=p.min(axis=0); high=p.max(axis=0)
    p=(p-(low+high)/2)*(1.1/max(high-low))
    uv=access(attr['TEXCOORD_0']); indices=access(prim['indices']).flatten()
    if len(indices)%3 or len(indices)>1500: raise ValueError('Unexpected mesh size')
    material=doc['materials'][prim['material']]
    texid=material['pbrMetallicRoughness']['baseColorTexture']['index']
    image=doc['images'][doc['textures'][texid]['source']]; view=doc['bufferViews'][image['bufferView']]
    start=view.get('byteOffset',0)
    im=Image.open(io.BytesIO(binary[start:start+view['byteLength']])).convert('RGBA').resize((128,128),Image.Resampling.LANCZOS)
    pixels=np.array(im,dtype=np.uint32); intensity=pixels[:,:,0]
    # Retain the source's honeycomb/frame pattern; turn its red emission green.
    green=(pixels[:,:,3]<<24)|((intensity//3)<<16)|(intensity<<8)|(intensity//8)
    lines=['/* Generated by tools/import_cave_shield.py; CC BY 4.0, assets/shield/CREDITS.md. */',
           'static const unsigned int cave_shield_texture[128*128] __attribute__((aligned(64))) = {']
    for row in green: lines.append(','.join('0x%08x'%int(c) for c in row)+',')
    lines+=['};','static const MdVertex cave_shield_mesh[] = {']
    for i in indices:
        lines.append(' {%s,0xffffffff,%s},'%(','.join(f'{x:.7f}f' for x in uv[i]),','.join(f'{x:.7f}f' for x in p[i])))
    lines+=['};','']
    target.write_text('\n'.join(lines))
    print(f'{len(indices)//3} triangles, {p.min(axis=0)} .. {p.max(axis=0)}, texture 128x128 RGBA (64 KiB)')

if __name__ == '__main__': convert(Path(sys.argv[1]),Path(sys.argv[2]))
